In [2]:
import requests

import pandas as pd

from bs4 import BeautifulSoup

print("Ready!")

Ready!

In [4]:
url = "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/canada-needs-more-grocery-competition"

headers = {

    "User-Agent": "Mozilla/5.0"

}

response = requests.get(url, headers=headers, timeout=20)

print("Status Code:", response.status_code)

print("HTML Length:", len(response.text))

Status Code: 200
HTML Length: 170367

In [36]:
soup = BeautifulSoup(response.text, "html.parser")



title = soup.find("h1")

print("Title:")

print(title.get_text(strip=True))

Title:
Canada Needs More Grocery Competition

In [38]:


paragraphs = soup.find_all("p")

print("Number of paragraphs:", len(paragraphs))


for i, p in enumerate(paragraphs[:10]):

    print(i, p.get_text(" ", strip=True))

Number of paragraphs: 294
0 June 27, 2023
1 This publication is not a legal document. It is intended to provide general information and is provided for convenience. To learn more, please refer to the full text of the Acts or contact the Competition Bureau.
2 For information on the Competition Bureau’s activities, please contact:
3 Information Centre Competition Bureau 50 Victoria Street Gatineau QC  K1A 0C9
4 Telephone: 819‑997‑4282 Telephone (toll-free in Canada): 1‑800‑348‑5358 TTY (for hearing impaired): 1‑866‑694‑8389 Fax: 819‑997‑0324 Website: www.competitionbureau.gc.ca
5 This publication can be made available in alternative formats upon request. Contact the Competition Bureau’s Information Centre at the numbers listed above.
6 Permission to reproduce
7 Except as otherwise specifically noted, the information in this publication may be reproduced, in part or in whole and by any means, without charge or further permission from the Competition Bureau, provided that due diligence is exercised in ensuring the accuracy of the information reproduced; that the Competition Bureau is identified as the source institution; and that the reproduction is not represented as an official version of the information reproduced or as having been made in affiliation with, or with the endorsement of, the Competition Bureau.
8 For permission to reproduce the information in this publication for commercial purposes, please fill out the Application for Crown Copyright Clearance at www.ic.gc.ca/copyright-request or contact the ISED Citizen Services Centre mentioned below.
9 ISED Citizen Services Centre Innovation, Science and Economic Development Canada C.D. Howe Building 235 Queen Street Ottawa, ON  K1A 0H5 Canada

In [10]:
main = soup.find("main")

print(main is not None)

if main:

    print(main.get_text(" ", strip=True)[:3000])

True
Canada Needs More Grocery Competition Competition Bureau Retail Grocery Market Study Report June 27, 2023 Copyright and permission to reproduce This publication is not a legal document. It is intended to provide general information and is provided for convenience. To learn more, please refer to the full text of the Acts or contact the Competition Bureau. For information on the Competition Bureau’s activities, please contact: Information Centre Competition Bureau 50 Victoria Street Gatineau QC  K1A 0C9 Telephone: 819‑997‑4282 Telephone (toll-free in Canada): 1‑800‑348‑5358 TTY (for hearing impaired): 1‑866‑694‑8389 Fax: 819‑997‑0324 Website: www.competitionbureau.gc.ca This publication can be made available in alternative formats upon request. Contact the Competition Bureau’s Information Centre at the numbers listed above. Permission to reproduce Except as otherwise specifically noted, the information in this publication may be reproduced, in part or in whole and by any means, without charge or further permission from the Competition Bureau, provided that due diligence is exercised in ensuring the accuracy of the information reproduced; that the Competition Bureau is identified as the source institution; and that the reproduction is not represented as an official version of the information reproduced or as having been made in affiliation with, or with the endorsement of, the Competition Bureau. For permission to reproduce the information in this publication for commercial purposes, please fill out the Application for Crown Copyright Clearance at www.ic.gc.ca/copyright-request or contact the ISED Citizen Services Centre mentioned below. ISED Citizen Services Centre Innovation, Science and Economic Development Canada C.D. Howe Building 235 Queen Street Ottawa, ON  K1A 0H5 Canada Telephone (toll-free in Canada): 1‑800‑328‑6189 Telephone (international): 613‑954‑5031 TTY (for hearing impaired): 1‑866‑694‑8389 Business hours: 8:30 a.m. to 5:00 p.m. (Eastern Time) Email: ISED@ised-isde.gc.ca © His Majesty the King in Right of Canada, as represented by the Minister of Industry, (2023). Date: 2023-06-27 Aussi offert en français sous le titre Le Canada a besoin de plus de concurrence dans le secteur de l’épicerie : Rapport de l’étude de marché sur l’épicerie de détail du Bureau de la concurrence Table of contents Executive summary Making the case for more grocery competition About the Competition Bureau How we collected information for this study Public opinion: Survey results and what we learned The state of the supermarket: Grocery competition in Canada Consolidation among Canada’s grocers Domestic grocer margins Property controls Online grocery: The new supermarket? Bringing international grocery players to Canada How other countries have increased grocery competition Informing consumers Canadians’ ideas for increasing grocery competition Recommendations to increase grocery competition in Canada How to contact the Competition Bureau Footnotes Canada Nee

In [12]:
main_paragraphs = main.find_all("p")

print("Paragraphs inside main:", len(main_paragraphs))

for i, p in enumerate(main_paragraphs[:20]):

    text = p.get_text(" ", strip=True)

    print(i, text[:300])

Paragraphs inside main: 294
0 June 27, 2023
1 This publication is not a legal document. It is intended to provide general information and is provided for convenience. To learn more, please refer to the full text of the Acts or contact the Competition Bureau.
2 For information on the Competition Bureau’s activities, please contact:
3 Information Centre Competition Bureau 50 Victoria Street Gatineau QC  K1A 0C9
4 Telephone: 819‑997‑4282 Telephone (toll-free in Canada): 1‑800‑348‑5358 TTY (for hearing impaired): 1‑866‑694‑8389 Fax: 819‑997‑0324 Website: www.competitionbureau.gc.ca
5 This publication can be made available in alternative formats upon request. Contact the Competition Bureau’s Information Centre at the numbers listed above.
6 Permission to reproduce
7 Except as otherwise specifically noted, the information in this publication may be reproduced, in part or in whole and by any means, without charge or further permission from the Competition Bureau, provided that due diligence is exercised in ensuring the accuracy of the information reproduced; that
8 For permission to reproduce the information in this publication for commercial purposes, please fill out the Application for Crown Copyright Clearance at www.ic.gc.ca/copyright-request or contact the ISED Citizen Services Centre mentioned below.
9 ISED Citizen Services Centre Innovation, Science and Economic Development Canada C.D. Howe Building 235 Queen Street Ottawa, ON  K1A 0H5 Canada
10 Telephone (toll-free in Canada): 1‑800‑328‑6189 Telephone (international): 613‑954‑5031 TTY (for hearing impaired): 1‑866‑694‑8389 Business hours: 8:30 a.m. to 5:00 p.m. (Eastern Time) Email: ISED@ised-isde.gc.ca
11 © His Majesty the King in Right of Canada, as represented by the Minister of Industry, (2023).
12 Date: 2023-06-27
13 Aussi offert en français sous le titre Le Canada a besoin de plus de concurrence dans le secteur de l’épicerie : Rapport de l’étude de marché sur l’épicerie de détail du Bureau de la concurrence
14
15 Canada Needs More Grocery Competition: Competition Bureau Retail Grocery Market Study Report PDF , 5.46 MB , 52 Pages
16 Canada’s grocery industry is concentrated. Most Canadians buy groceries in stores owned by a handful of grocery giants. In 2022, Canada’s three largest grocers—Loblaws, Sobeys, and Metro—collectively reported more than $100 billion in sales and earned more than $3.6 billion in profits.
17 For new players and regional independents, the Canadian grocery industry is tough to break into. Canada is a big country and opening new grocery stores Footnote 1 is expensive and difficult. The industry’s big players operate thousands of stores and are well entrenched in the shopping habits of Cana
18 In recent years, industry concentration has increased, and it has become more difficult than ever for businesses to enter, expand, and compete effectively. Furthermore, the price Canadians pay for groceries has been rising fast. Factors such as higher input costs, Russia's invasion of Ukraine, and s
19 Canada needs solutions to help bring grocery prices in check. More competition is a key part of the answer.

In [14]:


headings = main.find_all(["h1", "h2", "h3"])

for i, h in enumerate(headings):

    print(i, h.name, ":", h.get_text(" ", strip=True))

0 h1 : Canada Needs More Grocery Competition
1 h2 : Competition Bureau Retail Grocery Market Study Report
2 h2 : Copyright and permission to reproduce
3 h2 : Table of contents
4 h2 : Executive summary
5 h3 : On our use of plain language
6 h3 : Our Recommendations
7 h2 : Making the case for more grocery competition
8 h2 : About the Competition Bureau
9 h3 : The Bureau’s law enforcement mandate
10 h3 : Competition promotion: Helping governments create more competition
11 h2 : How we collected information for this study
12 h2 : Public opinion: Survey results and what we learned
13 h3 : Key takeaways
14 h3 : Public opinion survey results
15 h3 : How do social, economic and cultural factors shape the way Canadians buy groceries?
16 h3 : What we learned about grocery competition from Canadians
17 h3 : 1. Proximity matters
18 h3 : 2. The degree of grocery competition in urban and rural communities varies in meaningful ways
19 h3 : Remote, Northern, and Indigenous Communities
20 h3 : 3. Supermarkets are still the main option for consumers ...
21 h3 : 4. ... But online options are becoming more important
22 h3 : 5. Loyalty programs drive consumer decisions
23 h3 : Here’s what follows
24 h2 : The state of the supermarket: Grocery competition in Canada
25 h3 : Key takeaways
26 h3 : Canada’s grocery giants
27 h3 : Independent grocers in Canada
28 h3 : Differences between Rural and Urban communities
29 h3 : Barriers faced by independent grocers
30 h3 : Conclusion
31 h2 : Consolidation among Canada’s grocers
32 h3 : A history of grocery mergers in Canada
33 h3 : So, how did we get here?
34 h3 : Steps taken by the Bureau to protect grocery competition during merger reviews
35 h3 : Do Canada’s merger laws do enough to protect competition?
36 h2 : Domestic grocer margins
37 h3 : Key takeaways
38 h3 : Are increasing prices an indicator of competition problems?
39 h3 : Why doesn’t the Bureau stop companies from charging high prices?
40 h3 : Canadian grocers sell more than just groceries
41 h3 : Did Canada’s grocery giants cooperate with the Bureau’s study?
42 h3 : Canadian grocers’ food gross margins increased by a modest yet meaningful amount
43 h3 : What does modest but meaningful mean for Canadians?
44 h3 : Modest but meaningful margin changes can cause big changes in profits when food inflation is high
45 h3 : Additional analysis would help us better understand grocer profitability
46 h3 : What do modestly increasing margins tell us about competitive dynamics?
47 h2 : Property controls
48 h3 : Key takeaways
49 h3 : How do property controls affect grocery competition?
50 h3 : What effect do property controls have on grocery competition?
51 h3 : Conclusion on property controls
52 h2 : Online grocery: The new supermarket?
53 h3 : Key takeaways
54 h3 : Canada’s online grocery options
55 h3 : What are meal kit services, dark stores, and fulfillment centres?
56 h3 : Competition in online grocery
57 h3 : What about Amazon?
58 h3 : Challenges for new, online grocery businesses
59 h3 : Conclusion on online grocery competition
60 h2 : Bringing international grocery players to Canada
61 h3 : Key takeaways
62 h3 : Conclusion on competition from international grocers
63 h2 : How other countries have increased grocery competition
64 h3 : Key takeaways
65 h3 : 1. Grocery Codes of Conduct
66 h3 : 2. Property Controls
67 h3 : 3. Buying Groups
68 h3 : 4. Unit Pricing
69 h3 : 5. The Competitive Importance of Discount Grocers
70 h3 : The “ALDI effect”
71 h3 : Conclusion from international attempts to increase grocery competition
72 h2 : Informing consumers
73 h3 : Key takeaways
74 h3 : Unit pricing
75 h3 : Price comparison tools
76 h2 : Canadians’ ideas for increasing grocery competition
77 h3 : Key takeaways
78 h3 : Idea #1: Canada needs more grocery competition
79 h3 : Canada Needs More Competition
80 h3 : Idea #2: Large grocers should be broken up
81 h3 : Idea #3: Grocery prices should be regulated
82 h3 : Idea #4: Big grocers shouldn’t be allowed to buy smaller competitors
83 h3 : Idea #5: The government should stop big grocers from colluding with one another
84 h3 : Idea #6: Supply management raises grocery prices and should be abolished
85 h3 : Idea #7: Grocer profits are increasing, and the government should impose windfall taxes to recoup some of these profits
86 h3 : Idea #8: The government should encourage international grocers to enter Canada
87 h3 : Idea #9: The government needs to take action to stop the big grocers’ business practices that hurt suppliers and result in higher prices for consumers
88 h3 : Idea #10: “Shrinkflation” should be banned
89 h2 : Recommendations to increase grocery competition in Canada
90 h3 : Ideas for Governments across Canada
91 h3 : Commitments from the Bureau
92 h2 : How to contact the Competition Bureau
93 h2 : Footnotes

In [16]:
# 找到 Executive summary，作为正文起点

start_heading = None

for h in main.find_all(["h2", "h3"]):

    if h.get_text(" ", strip=True) == "Executive summary":

        start_heading = h

        break

print("Start heading:", start_heading.get_text(strip=True))

Start heading: Executive summary

In [30]:
content = []

for element in start_heading.find_all_next():

    

    if (

        element.name == "h2"

        and element.get_text(" ", strip=True)

        == "How to contact the Competition Bureau"

    ):

        break

    

    if element.name in ["h2", "h3", "p"]:

        text = element.get_text(" ", strip=True)

        if text:

            content.append(text)

print("Number of extracted elements:", len(content))

for item in content[:20]:

    print(item)

Number of extracted elements: 318
Canada’s grocery industry is concentrated. Most Canadians buy groceries in stores owned by a handful of grocery giants. In 2022, Canada’s three largest grocers—Loblaws, Sobeys, and Metro—collectively reported more than $100 billion in sales and earned more than $3.6 billion in profits.
For new players and regional independents, the Canadian grocery industry is tough to break into. Canada is a big country and opening new grocery stores Footnote 1 is expensive and difficult. The industry’s big players operate thousands of stores and are well entrenched in the shopping habits of Canadians.
In recent years, industry concentration has increased, and it has become more difficult than ever for businesses to enter, expand, and compete effectively. Furthermore, the price Canadians pay for groceries has been rising fast. Factors such as higher input costs, Russia's invasion of Ukraine, and supply chain disruptions have contributed to recent increases in the price of food. But we have also seen a longer-term trend that pre-dates those events, of Canada’s largest grocers increasing the amount they make on food sales.
Canada needs solutions to help bring grocery prices in check. More competition is a key part of the answer.
On our use of plain language
This report uses language that is different from the Bureau’s previous market study reports. Communicating clearly and accessibly with the public promotes transparency and accountability in the Bureau’s work. It also encourages compliance with the law and promotes awareness of important issues which may impact consumers and businesses. The Bureau is committed to using plain and accessible language wherever possible.
Our Recommendations
Competitive markets empower consumers and drive businesses to lower prices, improve product quality, innovate, and bring valuable new products to market. In this report, we make four recommendations to governments to improve competition in the grocery industry. They are designed to be flexible and provide principles-based guidance on actions that federal, provincial, and territorial governments across Canada can take. The Bureau recognizes that governments will need to consider and weigh other factors in deciding whether, and if so, how to implement these recommendations. However, the Bureau is committed to collaborating with decision-makers to help advance our recommendations in the most pro-competitive way possible.
Our recommendations are as follows:
The Bureau also needs to approach its work in the grocery industry with heightened vigilance and scrutiny to ensure that Canadians benefit from greater choice and more affordable groceries. We need to thoroughly and quickly investigate allegations of wrongdoing, and we need the power to act when issues arise. Therefore, in addition to the above recommendations for governments across Canada, the Bureau commits to taking the following three steps to better promote competition in the Canadian grocery industry:
Change will take time. These solutions will not bring Canadians’ grocery bills down immediately. But by acting now, governments at all levels can take steps toward creating a more competitive grocery industry in Canada.
top of page
Making the case for more grocery competition
Why does competition matter? In a nutshell, competition is the driver of Canada's economy . When our economy is more competitive, Canadian businesses and consumers benefit in meaningful ways.
Competition pushes businesses to innovate, to improve the products and services they offer, and to enhance the efficiency of their operations. When these things happen, consumers benefit from increased choice, higher quality goods and services, and lower prices.
Competition matters in all industries and sectors of our economy, but why is it so important in the grocery industry?
Canada’s grocery industry is concentrated . It can be difficult for small and medium-sized businesses to compete effectively against Canada’s grocery giants. It is also challenging for new businesses to enter the industry successfully.
Without changes in the competitive landscape, Canadians will not be able to fully benefit from competitive prices and product choices.
So what is the solution? In our view, Canada needs more grocery competition .
Governments at all levels need to take steps to encourage and support more grocery competition in Canada. We have laid out a path to do so in this report.

In [20]:
article_text = " ".join(content)

print("Clean text length:", len(article_text))

print()

print(article_text[:2000])

Clean text length: 61034

Canada’s grocery industry is concentrated. Most Canadians buy groceries in stores owned by a handful of grocery giants. In 2022, Canada’s three largest grocers—Loblaws, Sobeys, and Metro—collectively reported more than $100 billion in sales and earned more than $3.6 billion in profits. For new players and regional independents, the Canadian grocery industry is tough to break into. Canada is a big country and opening new grocery stores Footnote 1 is expensive and difficult. The industry’s big players operate thousands of stores and are well entrenched in the shopping habits of Canadians. In recent years, industry concentration has increased, and it has become more difficult than ever for businesses to enter, expand, and compete effectively. Furthermore, the price Canadians pay for groceries has been rising fast. Factors such as higher input costs, Russia's invasion of Ukraine, and supply chain disruptions have contributed to recent increases in the price of food. But we have also seen a longer-term trend that pre-dates those events, of Canada’s largest grocers increasing the amount they make on food sales. Canada needs solutions to help bring grocery prices in check. More competition is a key part of the answer. On our use of plain language This report uses language that is different from the Bureau’s previous market study reports. Communicating clearly and accessibly with the public promotes transparency and accountability in the Bureau’s work. It also encourages compliance with the law and promotes awareness of important issues which may impact consumers and businesses. The Bureau is committed to using plain and accessible language wherever possible. Our Recommendations Competitive markets empower consumers and drive businesses to lower prices, improve product quality, innovate, and bring valuable new products to market. In this report, we make four recommendations to governments to improve competition in the grocery industry. They are designed to be flexible and p

In [22]:
article_data = {

    "article_id": [1],

    "title": ["Canada Needs More Grocery Competition"],

    "publication_date": ["2023-06-27"],

    "source": ["Competition Bureau Canada"],

    "source_url": [url],

    "article_text": [article_text]

}

df_articles = pd.DataFrame(article_data)

df_articles

,article_id,title,publication_date,source,source_url,article_text
0,1,Canada Needs More Grocery Competition,2023-06-27,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,Canada’s grocery industry is concentrated. Mos...

In [32]:


df_articles["publication_date"] = pd.to_datetime(

    df_articles["publication_date"]

)



df_articles["word_count"] = (

    df_articles["article_text"]

    .str.split()

    .str.len()

)



df_articles["year"] = df_articles["publication_date"].dt.year

df_articles["month"] = df_articles["publication_date"].dt.month

df_articles[

    ["article_id", "title", "publication_date", "word_count", "year", "month"]

]

,article_id,title,publication_date,word_count,year,month
0,1,Canada Needs More Grocery Competition,2023-06-27,9725,2023,6

In [34]:


text_lower = df_articles.loc[0, "article_text"].lower()



keywords = {

    "competition": "competition",

    "price": "price",

    "online": "online",

    "ecommerce": "e-commerce",

    "consumer": "consumer",

    "grocery": "grocery"

}



for column_name, keyword in keywords.items():

    df_articles[column_name + "_mentions"] = text_lower.count(keyword)

df_articles[

    [

        "title",

        "word_count",

        "competition_mentions",

        "price_mentions",

        "online_mentions",

        "ecommerce_mentions",

        "consumer_mentions",

        "grocery_mentions"

    ]

]

,title,word_count,competition_mentions,price_mentions,online_mentions,ecommerce_mentions,consumer_mentions,grocery_mentions
0,Canada Needs More Grocery Competition,9725,128,81,46,0,55,185

In [42]:
import requests

import pandas as pd

from bs4 import BeautifulSoup

import re

def scrape_article(url):

    # Set request headers

    headers = {

        "User-Agent": "Mozilla/5.0"

    }

    # Request the webpage

    response = requests.get(url, headers=headers, timeout=20)

    response.raise_for_status()

    # Parse HTML

    soup = BeautifulSoup(response.text, "html.parser")

    main = soup.find("main")

    if main is None:

        return None

    # Extract page title

    h1 = main.find("h1")

    title = h1.get_text(" ", strip=True) if h1 else "Unknown"

    # Extract publication date

    page_text = main.get_text(" ", strip=True)

    date_match = re.search(

        r"(January|February|March|April|May|June|July|August|September|October|November|December)"

        r"\s+\d{1,2},\s+\d{4}",

        page_text

    )

    publication_date = date_match.group(0) if date_match else None

    # Find the beginning of the main article content

    start_heading = None

    for h in main.find_all(["h2", "h3"]):

        heading_text = h.get_text(" ", strip=True)

        if heading_text in [

            "Executive summary",

            "Overview",

            "Introduction"

        ]:

            start_heading = h

            break

    # Select elements to extract

    if start_heading:

        elements = start_heading.find_all_next()

    else:

        elements = main.find_all(["h2", "h3", "p"])

    # Extract article content

    content = []

    for element in elements:

        text = element.get_text(" ", strip=True)

        if (

            element.name == "h2"

            and text in [

                "How to contact the Competition Bureau",

                "Footnotes"

            ]

        ):

            break

        if element.name in ["h2", "h3", "p"] and text:

            content.append(text)

    # Combine and clean text

    article_text = " ".join(content)

    article_text = re.sub(r"\s+", " ", article_text).strip()

    # Return extracted data

    return {

        "title": title,

        "publication_date": publication_date,

        "source": "Competition Bureau Canada",

        "source_url": url,

        "article_text": article_text,

        "word_count": len(article_text.split())

    }

# Test the scraping function

url = "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/canada-needs-more-grocery-competition"

result = scrape_article(url)

print("Title:", result["title"])

print("Date:", result["publication_date"])

print("Word Count:", result["word_count"])

print()

print(result["article_text"][:1000])

Title: Canada Needs More Grocery Competition
Date: June 27, 2023
Word Count: 9725

Canada’s grocery industry is concentrated. Most Canadians buy groceries in stores owned by a handful of grocery giants. In 2022, Canada’s three largest grocers—Loblaws, Sobeys, and Metro—collectively reported more than $100 billion in sales and earned more than $3.6 billion in profits. For new players and regional independents, the Canadian grocery industry is tough to break into. Canada is a big country and opening new grocery stores Footnote 1 is expensive and difficult. The industry’s big players operate thousands of stores and are well entrenched in the shopping habits of Canadians. In recent years, industry concentration has increased, and it has become more difficult than ever for businesses to enter, expand, and compete effectively. Furthermore, the price Canadians pay for groceries has been rising fast. Factors such as higher input costs, Russia's invasion of Ukraine, and supply chain disruptions have contributed to recent increases in the price of food. But we have also seen a

In [85]:
import time

urls = [

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/market-study-notice-competition-canadas-grocery-sector",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/canada-needs-more-grocery-competition",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/call-out-information-about-property-controls-canadian-grocery-industry",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/publications/competitor-property-controls-and-competition-act",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/notice-behind-price-tag-examining-food-supply-chain",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/education-and-outreach/publications/assessing-progress-competition-bureaus-retail-grocery-recommendations",

    "https://competition-bureau.canada.ca/en/how-we-foster-competition/behind-price-tag-examination-food-supply-chain"

]

results = []

for i, url in enumerate(urls, start=1):

    try:

        article = scrape_article(url)

        if article is not None:

            article["article_id"] = i

            results.append(article)

            print(

                f"Success: {article['title']} "

                f"| Date: {article['publication_date']} "

                f"| Words: {article['word_count']}"

            )

        time.sleep(2)

    except Exception as e:

        print(f"Failed: {url}")

        print("Error:", e)

Success: Market Study Notice: Competition in Canada’s Grocery Sector | Date: October 24, 2022 | Words: 1516
Success: Canada Needs More Grocery Competition | Date: June 27, 2023 | Words: 15167
Success: Call-out for information about property controls in the Canadian grocery industry | Date: October 21, 2024 | Words: 619
Success: Competitor property controls and the Competition Act | Date: June 4, 2025 | Words: 6250
Success: Notice: Behind the price tag: Examining the food supply chain | Date: June 16, 2026 | Words: 2321
Success: Assessing progress on the Competition Bureau’s retail grocery recommendations | Date: September 3, 2026 | Words: 1008
Success: Behind the price tag: An examination of the food supply chain | Date: June 16, 2026 | Words: 435

In [48]:
print(results[1]["title"])

print()

print(results[1]["article_text"])

Market Study Notice: Competition in Canada’s Grocery Sector

The Bureau’s public consultation on Market Study Notice: Competition in Canada’s Grocery Sector took place from October 24, 2022 to December 16, 2022 and is now closed. The Bureau will post the written responses submitted for the consultation. Table of contents Notice of Study Purpose of the Study Scope of the Study Outcomes of the Study Process and Study Milestones Getting Involved Premise of the Study Limitations of the Study Confidentiality Annex A: Foreign Studies of Grocery Competition

In [53]:
def scrape_article(url):

    headers = {

        "User-Agent": "Mozilla/5.0"

    }

    response = requests.get(url, headers=headers, timeout=20)

    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    main = soup.find("main")

    if main is None:

        return None

    # Extract title

    h1 = main.find("h1")

    title = h1.get_text(" ", strip=True) if h1 else "Unknown"

    # Extract publication date

    page_text = main.get_text(" ", strip=True)

    date_match = re.search(

        r"(January|February|March|April|May|June|July|August|September|October|November|December)"

        r"\s+\d{1,2},\s+\d{4}",

        page_text

    )

    publication_date = date_match.group(0) if date_match else None

    # Remove elements that are not useful for text analysis

    for tag in main.find_all([

        "script",

        "style",

        "nav",

        "form",

        "button"

    ]):

        tag.decompose()

    # Extract headings, paragraphs, and list items

    content = []

    for element in main.find_all(["h2", "h3", "p", "li"]):

        text = element.get_text(" ", strip=True)

        if not text:

            continue

        # Stop before administrative sections

        if element.name == "h2" and text in [

            "How to contact the Competition Bureau",

            "Footnotes"

        ]:

            break

        content.append(text)

    # Remove duplicate consecutive text

    cleaned_content = []

    for text in content:

        if not cleaned_content or text != cleaned_content[-1]:

            cleaned_content.append(text)

    # Combine and clean text

    article_text = " ".join(cleaned_content)

    article_text = re.sub(r"\s+", " ", article_text).strip()

    return {

        "title": title,

        "publication_date": publication_date,

        "source": "Competition Bureau Canada",

        "source_url": url,

        "article_text": article_text,

        "word_count": len(article_text.split())

    }

In [55]:
import time

results = []

for i, url in enumerate(urls, start=1):

    try:

        article = scrape_article(url)

        if article is not None:

            article["article_id"] = i

            results.append(article)

            print(

                f"Success: {article['title']} "

                f"| Date: {article['publication_date']} "

                f"| Words: {article['word_count']}"

            )

        time.sleep(2)

    except Exception as e:

        print(f"Failed: {url}")

Success: Canada Needs More Grocery Competition | Date: June 27, 2023 | Words: 15925
Success: Market Study Notice: Competition in Canada’s Grocery Sector | Date: October 24, 2022 | Words: 1598
Success: Assessing progress on the Competition Bureau’s retail grocery recommendations | Date: September 3, 2026 | Words: 1041

In [61]:
for i, article in enumerate(results):

    print("=" * 80)

    print("ARTICLE:", i + 1)

    print("TITLE:", article["title"])

    print("WORD COUNT:", article["word_count"])

    print()

    print(article["article_text"][:1500])

    print()

================================================================================
ARTICLE: 1
TITLE: Canada Needs More Grocery Competition
WORD COUNT: 15925

Competition Bureau Retail Grocery Market Study Report June 27, 2023 Copyright and permission to reproduce This publication is not a legal document. It is intended to provide general information and is provided for convenience. To learn more, please refer to the full text of the Acts or contact the Competition Bureau. For information on the Competition Bureau’s activities, please contact: Information Centre Competition Bureau 50 Victoria Street Gatineau QC K1A 0C9 Telephone: 819‑997‑4282 Telephone (toll-free in Canada): 1‑800‑348‑5358 TTY (for hearing impaired): 1‑866‑694‑8389 Fax: 819‑997‑0324 Website: www.competitionbureau.gc.ca This publication can be made available in alternative formats upon request. Contact the Competition Bureau’s Information Centre at the numbers listed above. Permission to reproduce Except as otherwise specifically noted, the information in this publication may be reproduced, in part or in whole and by any means, without charge or further permission from the Competition Bureau, provided that due diligence is exercised in ensuring the accuracy of the information reproduced; that the Competition Bureau is identified as the source institution; and that the reproduction is not represented as an official version of the information reproduced or as having been made in affiliation with, or with the endorsement of, the Competition Bureau. For permission to reproduce the information in this publication for commercial purposes, please fill out the Application f

================================================================================
ARTICLE: 2
TITLE: Market Study Notice: Competition in Canada’s Grocery Sector
WORD COUNT: 1598

The Bureau’s public consultation on Market Study Notice: Competition in Canada’s Grocery Sector took place from October 24, 2022 to December 16, 2022 and is now closed. The Bureau will post the written responses submitted for the consultation. Table of contents Notice of Study Purpose of the Study Scope of the Study Outcomes of the Study Process and Study Milestones Getting Involved Premise of the Study Limitations of the Study Confidentiality Annex A: Foreign Studies of Grocery Competition Footnotes Notice of Study The Competition Bureau (Bureau) is commencing a market study to promote competition in Canada’s retail grocery sector (Study). A market study allows the Bureau to examine the competitive dynamics of an industry. This Study will explore how governments across Canada can act to promote greater competition in the retail grocery sector. Footnote 1 Market studies are distinct from, and are generally not intended to motivate, law enforcement activities under the Competition Act (Act). Footnote 2 In undertaking this Study, the Bureau is not examining any specific allegations of wrongdoing. However, should the Bureau uncover any evidence during the Study that the Act has been contravened, the Bureau will investigate and take appropriate action. Purpose of the Study The Canadian grocery sector is concentrated. Many Canadians buy groceries from retail chains operated by one of three companies: Loblaws, Sobeys, and Metro. Other important retailers include Costco and Walmart,

================================================================================
ARTICLE: 3
TITLE: Assessing progress on the Competition Bureau’s retail grocery recommendations
WORD COUNT: 1041

September 3, 2026 In 2023, we published the findings of our retail grocery market study - Canada Needs More Grocery Competition . In our report, we committed to a three-year follow-up to assess progress on our recommendations to governments. This follow-up highlights the steps that have been taken following the publication of our report. While progress has been made, we continue to encourage governments across Canada to implement the recommendations of our report. Food affordability remains a key concern for Canadians, and more competition is key to lower prices and greater choice. On this page Overview Competition Bureau recommendations Legislative and policy progress Bureau actions Looking ahead Overview Food prices remain a major concern for Canadians. The Bank of Canada reports that grocery prices have surged by 22% from 2022 to 2025 , compared to an increase of 13% for other consumer prices. In December 2025, food inflation rose to 5%, the highest rate since late 2023. Several factors are pushing food prices up. These include higher import costs, supply chain disruptions, a weaker Canadian dollar, and extreme weather. Lower-income households have been particularly affected by grocery price increases, with food purchases representing over 27% of their disposable income—compared to just 5% in those in the highest income households. Most Canadians still buy their groceries from one of only five companies: Loblaw, Sobeys, Metro, Costco, and Walmart. Even if Canadians don’t s

In [59]:
def scrape_article(url):

    headers = {

        "User-Agent": "Mozilla/5.0"

    }

    response = requests.get(url, headers=headers, timeout=20)

    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    main = soup.find("main")

    if main is None:

        return None

    # Extract title

    h1 = main.find("h1")

    title = h1.get_text(" ", strip=True) if h1 else "Unknown"

    # Extract publication date

    page_text = main.get_text(" ", strip=True)

    date_match = re.search(

        r"(January|February|March|April|May|June|July|August|September|October|November|December)"

        r"\s+\d{1,2},\s+\d{4}",

        page_text

    )

    publication_date = date_match.group(0) if date_match else None

    # Remove unnecessary HTML elements

    for tag in main.find_all(["script", "style", "nav", "form", "button"]):

        tag.decompose()

    # Identify possible content starting points

    start_headings = [

        "Executive summary",

        "Notice of Study",

        "Overview",

        "Introduction"

    ]

    start_element = None

    for element in main.find_all(["h2", "h3"]):

        text = element.get_text(" ", strip=True)

        if text in start_headings:

            start_element = element

            break

    # Extract content

    if start_element:

        elements = start_element.find_all_next(["h2", "h3", "p", "li"])

    else:

        elements = main.find_all(["h2", "h3", "p", "li"])

    content = []

    for element in elements:

        text = element.get_text(" ", strip=True)

        if not text:

            continue

        if element.name == "h2" and text in [

            "How to contact the Competition Bureau",

            "Footnotes"

        ]:

            break

        content.append(text)

    # Remove duplicate consecutive elements

    cleaned_content = []

    for text in content:

        if not cleaned_content or text != cleaned_content[-1]:

            cleaned_content.append(text)

    # Combine and clean text

    article_text = " ".join(cleaned_content)

    article_text = re.sub(r"\s+", " ", article_text).strip()

    return {

        "title": title,

        "publication_date": publication_date,

        "source": "Competition Bureau Canada",

        "source_url": url,

        "article_text": article_text,

        "word_count": len(article_text.split())

    }

In [63]:
test_result = scrape_article(urls[0])

print("Title:", test_result["title"])

print("Word Count:", test_result["word_count"])

print()

print(test_result["article_text"][:1000])

Title: Canada Needs More Grocery Competition
Word Count: 15167

Canada’s grocery industry is concentrated. Most Canadians buy groceries in stores owned by a handful of grocery giants. In 2022, Canada’s three largest grocers—Loblaws, Sobeys, and Metro—collectively reported more than $100 billion in sales and earned more than $3.6 billion in profits. For new players and regional independents, the Canadian grocery industry is tough to break into. Canada is a big country and opening new grocery stores Footnote 1 is expensive and difficult. The industry’s big players operate thousands of stores and are well entrenched in the shopping habits of Canadians. In recent years, industry concentration has increased, and it has become more difficult than ever for businesses to enter, expand, and compete effectively. Furthermore, the price Canadians pay for groceries has been rising fast. Factors such as higher input costs, Russia's invasion of Ukraine, and supply chain disruptions have contributed to recent increases in the price of food. But we have also seen a

In [65]:
import time

results = []

for i, url in enumerate(urls, start=1):

    try:

        article = scrape_article(url)

        if article is not None:

            article["article_id"] = i

            results.append(article)

            print(

                f"Success: {article['title']} "

                f"| Date: {article['publication_date']} "

                f"| Words: {article['word_count']}"

            )

        time.sleep(2)

    except Exception as e:

        print(f"Failed: {url}")

        print("Error:", e)
df_web = pd.DataFrame(results)

df_web[

    [

        "article_id",

        "title",

        "publication_date",

        "word_count"

    ]

]

Success: Canada Needs More Grocery Competition | Date: June 27, 2023 | Words: 15167
Success: Market Study Notice: Competition in Canada’s Grocery Sector | Date: October 24, 2022 | Words: 1516
Success: Assessing progress on the Competition Bureau’s retail grocery recommendations | Date: September 3, 2026 | Words: 1008

,article_id,title,publication_date,word_count
0,1,Canada Needs More Grocery Competition,"June 27, 2023",15167
1,2,Market Study Notice: Competition in Canada’s G...,"October 24, 2022",1516
2,3,Assessing progress on the Competition Bureau’s...,"September 3, 2026",1008

In [67]:
# Convert publication_date to datetime

df_web["publication_date"] = pd.to_datetime(

    df_web["publication_date"],

    errors="coerce"

)

# Create year and month variables

df_web["year"] = df_web["publication_date"].dt.year

df_web["month"] = df_web["publication_date"].dt.month

# Check the result

df_web[

    [

        "article_id",

        "title",

        "publication_date",

        "year",

        "month",

        "word_count"

    ]

]

,article_id,title,publication_date,year,month,word_count
0,1,Canada Needs More Grocery Competition,2023-06-27,2023,6,15167
1,2,Market Study Notice: Competition in Canada’s G...,2022-10-24,2022,10,1516
2,3,Assessing progress on the Competition Bureau’s...,2026-09-03,2026,9,1008

In [69]:
# Create a cleaned text variable for analysis

df_web["clean_text"] = (

    df_web["article_text"]

    .str.lower()

    .str.replace(r"\s+", " ", regex=True)

    .str.strip()

)

df_web[

    [

        "article_id",

        "title",

        "word_count",

        "clean_text"

    ]

].head()

,article_id,title,word_count,clean_text
0,1,Canada Needs More Grocery Competition,15167,canada’s grocery industry is concentrated. mos...
1,2,Market Study Notice: Competition in Canada’s G...,1516,the competition bureau (bureau) is commencing ...
2,3,Assessing progress on the Competition Bureau’s...,1008,food prices remain a major concern for canadia...

In [71]:
# Define keywords for text analysis

keywords = {

    "competition_mentions": "competition",

    "price_mentions": "price",

    "grocery_mentions": "grocery",

    "consumer_mentions": "consumer",

    "online_mentions": "online"

}

# Count keyword occurrences

for column, keyword in keywords.items():

    df_web[column] = (

        df_web["clean_text"]

        .str.count(rf"\b{keyword}\w*\b")

    )

df_web[

    [

        "article_id",

        "title",

        "competition_mentions",

        "price_mentions",

        "grocery_mentions",

        "consumer_mentions",

        "online_mentions"

    ]

]

,article_id,title,competition_mentions,price_mentions,grocery_mentions,consumer_mentions,online_mentions
0,1,Canada Needs More Grocery Competition,176,132,282,84,76
1,2,Market Study Notice: Competition in Canada’s G...,25,7,20,2,0
2,3,Assessing progress on the Competition Bureau’s...,18,17,19,4,0

In [73]:
# Check missing values

print("Missing values:")

print(df_web.isnull().sum())

print()

# Check duplicate URLs

print("Duplicate URLs:")

print(df_web["source_url"].duplicated().sum())

print()

# Check duplicate titles

print("Duplicate titles:")

print(df_web["title"].duplicated().sum())

print()

# Check article lengths

print("Word count summary:")

print(df_web["word_count"].describe())

Missing values:
title                   0
publication_date        0
source                  0
source_url              0
article_text            0
word_count              0
article_id              0
year                    0
month                   0
clean_text              0
competition_mentions    0
price_mentions          0
grocery_mentions        0
consumer_mentions       0
online_mentions         0
dtype: int64

Duplicate URLs:
0

Duplicate titles:
0

Word count summary:
count        3.000000
mean      5897.000000
std       8032.072647
min       1008.000000
25%       1262.000000
50%       1516.000000
75%       8341.500000
max      15167.000000
Name: word_count, dtype: float64

In [75]:
# Select final variables

web_articles_clean = df_web[

    [

        "article_id",

        "title",

        "publication_date",

        "year",

        "month",

        "source",

        "source_url",

        "word_count",

        "competition_mentions",

        "price_mentions",

        "grocery_mentions",

        "consumer_mentions",

        "online_mentions",

        "article_text"

    ]

].copy()

web_articles_clean

,article_id,title,publication_date,year,month,source,source_url,word_count,competition_mentions,price_mentions,grocery_mentions,consumer_mentions,online_mentions,article_text
0,1,Canada Needs More Grocery Competition,2023-06-27,2023,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,15167,176,132,282,84,76,Canada’s grocery industry is concentrated. Mos...
1,2,Market Study Notice: Competition in Canada’s G...,2022-10-24,2022,10,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1516,25,7,20,2,0,The Competition Bureau (Bureau) is commencing ...
2,3,Assessing progress on the Competition Bureau’s...,2026-09-03,2026,9,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1008,18,17,19,4,0,Food prices remain a major concern for Canadia...

In [77]:
web_articles_clean.to_csv(

    "web_articles_clean.csv",

    index=False,

    encoding="utf-8"

)

print("web_articles_clean.csv saved successfully.")

web_articles_clean.csv saved successfully.

In [79]:
check_web = pd.read_csv("web_articles_clean.csv")

print(check_web.shape)

print(check_web.columns.tolist())

check_web.head()

(3, 14)
['article_id', 'title', 'publication_date', 'year', 'month', 'source', 'source_url', 'word_count', 'competition_mentions', 'price_mentions', 'grocery_mentions', 'consumer_mentions', 'online_mentions', 'article_text']

,article_id,title,publication_date,year,month,source,source_url,word_count,competition_mentions,price_mentions,grocery_mentions,consumer_mentions,online_mentions,article_text
0,1,Canada Needs More Grocery Competition,2023-06-27,2023,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,15167,176,132,282,84,76,Canada’s grocery industry is concentrated. Mos...
1,2,Market Study Notice: Competition in Canada’s G...,2022-10-24,2022,10,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1516,25,7,20,2,0,The Competition Bureau (Bureau) is commencing ...
2,3,Assessing progress on the Competition Bureau’s...,2026-09-03,2026,9,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1008,18,17,19,4,0,Food prices remain a major concern for Canadia...

In [81]:
import os

print(os.getcwd())

/Users/yuanquan0901

In [83]:
web_articles_clean.to_csv(

    "web_articles_clean_excel.csv",

    index=False,

    encoding="utf-8-sig"

)

print("Excel-compatible CSV saved successfully.")

Excel-compatible CSV saved successfully.

In [87]:
import pandas as pd

import re

df_web = pd.DataFrame(results)

df_web["publication_date"] = pd.to_datetime(

    df_web["publication_date"],

    errors="coerce"

)

df_web["year"] = df_web["publication_date"].dt.year

df_web["month"] = df_web["publication_date"].dt.month

df_web["clean_text"] = (

    df_web["article_text"]

    .str.lower()

    .str.replace(r"\s+", " ", regex=True)

    .str.strip()

)

keywords = {

    "competition_mentions": "competition",

    "price_mentions": "price",

    "grocery_mentions": "grocery",

    "consumer_mentions": "consumer",

    "online_mentions": "online"

}

for column, keyword in keywords.items():

    df_web[column] = (

        df_web["clean_text"]

        .str.count(rf"\b{keyword}\w*\b")

    )

for column in keywords.keys():

    rate_column = column.replace("_mentions", "_per_1000_words")

    df_web[rate_column] = (

        df_web[column] / df_web["word_count"] * 1000

    ).round(2)

print(df_web.shape)

df_web[

    [

        "article_id",

        "title",

        "year",

        "word_count",

        "competition_mentions",

        "competition_per_1000_words",

        "price_mentions",

        "price_per_1000_words"

    ]

]

(7, 20)

,article_id,title,year,word_count,competition_mentions,competition_per_1000_words,price_mentions,price_per_1000_words
0,1,Market Study Notice: Competition in Canada’s G...,2022,1516,25,16.49,7,4.62
1,2,Canada Needs More Grocery Competition,2023,15167,176,11.60,132,8.70
2,3,Call-out for information about property contro...,2024,619,10,16.16,1,1.62
3,4,Competitor property controls and the Competiti...,2025,6250,124,19.84,5,0.80
4,5,Notice: Behind the price tag: Examining the fo...,2026,2321,37,15.94,15,6.46
5,6,Assessing progress on the Competition Bureau’s...,2026,1008,18,17.86,17,16.87
6,7,Behind the price tag: An examination of the fo...,2026,435,15,34.48,4,9.20

In [89]:
web_articles_clean = df_web[

    [

        "article_id",

        "title",

        "publication_date",

        "year",

        "month",

        "source",

        "source_url",

        "word_count",

        "competition_mentions",

        "price_mentions",

        "grocery_mentions",

        "consumer_mentions",

        "online_mentions",

        "competition_per_1000_words",

        "price_per_1000_words",

        "grocery_per_1000_words",

        "consumer_per_1000_words",

        "online_per_1000_words",

        "article_text"

    ]

].copy()

web_articles_clean["article_text"] = (

    web_articles_clean["article_text"]

    .str.replace(r"[\r\n]+", " ", regex=True)

    .str.replace(r"\s+", " ", regex=True)

    .str.strip()

)

web_articles_clean.to_csv(

    "web_articles_clean.csv",

    index=False,

    encoding="utf-8-sig"

)

print(web_articles_clean.shape)

print(web_articles_clean.isnull().sum())

print("Duplicate URLs:", web_articles_clean["source_url"].duplicated().sum())

print("Duplicate titles:", web_articles_clean["title"].duplicated().sum())

web_articles_clean.head(7)

(7, 19)
article_id                    0
title                         0
publication_date              0
year                          0
month                         0
source                        0
source_url                    0
word_count                    0
competition_mentions          0
price_mentions                0
grocery_mentions              0
consumer_mentions             0
online_mentions               0
competition_per_1000_words    0
price_per_1000_words          0
grocery_per_1000_words        0
consumer_per_1000_words       0
online_per_1000_words         0
article_text                  0
dtype: int64
Duplicate URLs: 0
Duplicate titles: 0

,article_id,title,publication_date,year,month,source,source_url,word_count,competition_mentions,price_mentions,grocery_mentions,consumer_mentions,online_mentions,competition_per_1000_words,price_per_1000_words,grocery_per_1000_words,consumer_per_1000_words,online_per_1000_words,article_text
0,1,Market Study Notice: Competition in Canada’s G...,2022-10-24,2022,10,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1516,25,7,20,2,0,16.49,4.62,13.19,1.32,0.00,The Competition Bureau (Bureau) is commencing ...
1,2,Canada Needs More Grocery Competition,2023-06-27,2023,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,15167,176,132,282,84,76,11.60,8.70,18.59,5.54,5.01,Canada’s grocery industry is concentrated. Mos...
2,3,Call-out for information about property contro...,2024-10-21,2024,10,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,619,10,1,7,1,0,16.16,1.62,11.31,1.62,0.00,"October 21, 2024 The Competition Bureau is inv..."
3,4,Competitor property controls and the Competiti...,2025-06-04,2025,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,6250,124,5,2,0,0,19.84,0.80,0.32,0.00,0.00,Legal standing This publication is not a legal...
4,5,Notice: Behind the price tag: Examining the fo...,2026-06-16,2026,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,2321,37,15,3,9,4,15.94,6.46,1.29,3.88,1.72,The Competition Bureau is examining how the fo...
5,6,Assessing progress on the Competition Bureau’s...,2026-09-03,2026,9,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,1008,18,17,19,4,0,17.86,16.87,18.85,3.97,0.00,Food prices remain a major concern for Canadia...
6,7,Behind the price tag: An examination of the fo...,2026-06-16,2026,6,Competition Bureau Canada,https://competition-bureau.canada.ca/en/how-we...,435,15,4,6,2,0,34.48,9.20,13.79,4.60,0.00,Latest update: Competition Bureau concerned gr...

In [91]:
import os

print(os.path.abspath("web_articles_clean.csv"))

check = pd.read_csv("web_articles_clean.csv")

print("Shape:", check.shape)

print("Columns:", len(check.columns))

print("Duplicate URLs:", check["source_url"].duplicated().sum())

/Users/yuanquan0901/web_articles_clean.csv
Shape: (7, 19)
Columns: 19
Duplicate URLs: 0