In [1]:
import pandas as pd

file_path = "/Users/yuanquan0901/Desktop/BSMM 8730/group project/20100056.csv"

df = pd.read_csv(file_path)

print("Shape:", df.shape)

df.head()

Shape: (79434, 17)

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Sales,Adjustments,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859481,1.1.1.1,41377009.0,NaN,NaN,NaN,0
1,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859483,1.1.1.2,50417235.0,NaN,NaN,NaN,0
2,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,81,thousands,3,v1446859482,1.1.2.1,1110045.0,NaN,NaN,NaN,0
3,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859484,1.1.2.2,1236885.0,NaN,NaN,NaN,0
4,2017-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859485,1.2.1.1,10162441.0,NaN,NaN,NaN,0

In [3]:
print(df.columns.tolist())

print("\nData types:")

print(df.dtypes)

print("\nMissing values:")

print(df.isnull().sum())

print("\nUnique values:")

print(df.nunique())

['REF_DATE', 'GEO', 'DGUID', 'North American Industry Classification System (NAICS)', 'Sales', 'Adjustments', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']

Data types:
REF_DATE                                                  object
GEO                                                       object
DGUID                                                     object
North American Industry Classification System (NAICS)     object
Sales                                                     object
Adjustments                                               object
UOM                                                       object
UOM_ID                                                     int64
SCALAR_FACTOR                                             object
SCALAR_ID                                                  int64
VECTOR                                                    object
COORDINATE                                                object
VALUE                                                    float64
STATUS                                                    object
SYMBOL                                                   float64
TERMINATED                                               float64
DECIMALS                                                   int64
dtype: object

Missing values:
REF_DATE                                                     0
GEO                                                          0
DGUID                                                        0
North American Industry Classification System (NAICS)        0
Sales                                                        0
Adjustments                                                  0
UOM                                                          0
UOM_ID                                                       0
SCALAR_FACTOR                                                0
SCALAR_ID                                                    0
VECTOR                                                       0
COORDINATE                                                   0
VALUE                                                    10319
STATUS                                                   39321
SYMBOL                                                   79434
TERMINATED                                               79434
DECIMALS                                                     0
dtype: int64

Unique values:
REF_DATE                                                   114
GEO                                                         23
DGUID                                                       23
North American Industry Classification System (NAICS)       30
Sales                                                        2
Adjustments                                                  2
UOM                                                          1
UOM_ID                                                       1
SCALAR_FACTOR                                                1
SCALAR_ID                                                    1
VECTOR                                                     738
COORDINATE                                                 738
VALUE                                                    63773
STATUS                                                       8
SYMBOL                                                       0
TERMINATED                                                   0
DECIMALS                                                     1
dtype: int64

In [5]:
print("Date range:")

print(df["REF_DATE"].min(), "to", df["REF_DATE"].max())

print("\nGeographies:")

print(df["GEO"].unique())

print("\nSales types:")

print(df["Sales"].value_counts())

print("\nAdjustments:")

print(df["Adjustments"].value_counts())

print("\nUnits:")

print(df["UOM"].value_counts())

print("\nScalar factors:")

print(df["SCALAR_FACTOR"].value_counts())

print("\nStatus:")

print(df["STATUS"].value_counts(dropna=False))

Date range:
2017-01 to 2026-06

Geographies:
['Canada' 'Newfoundland and Labrador' 'Prince Edward Island' 'Nova Scotia'
 'New Brunswick' 'Quebec' 'Montréal, Quebec' 'Ontario' 'Toronto, Ontario'
 'Manitoba' 'Saskatchewan' 'Alberta' 'British Columbia'
 'Vancouver, British Columbia' 'Yukon' 'Northwest Territories' 'Nunavut'
 'Quebec, Quebec' 'Gatineau, Quebec' 'Ottawa, Ontario'
 'Winnipeg, Manitoba' 'Calgary, Alberta' 'Edmonton, Alberta']

Sales types:
Sales
Total retail sales         79206
Retail e-commerce sales      228
Name: count, dtype: int64

Adjustments:
Adjustments
Unadjusted             74097
Seasonally adjusted     5337
Name: count, dtype: int64

Units:
UOM
Dollars    79434
Name: count, dtype: int64

Scalar factors:
SCALAR_FACTOR
thousands    79434
Name: count, dtype: int64

Status:
STATUS
NaN    39321
A      16862
x       8980
B       6307
C       4134
D       1803
F        783
E        688
..       556
Name: count, dtype: int64

In [7]:
missing_value_rows = df[df["VALUE"].isna()]

print("Rows with missing VALUE:", len(missing_value_rows))

print("\nMissing VALUE by status:")

print(

    missing_value_rows["STATUS"]

    .value_counts(dropna=False)

)

print("\nMissing VALUE by sales type:")

print(

    missing_value_rows["Sales"]

    .value_counts()

)

print("\nMissing VALUE by adjustment:")

print(

    missing_value_rows["Adjustments"]

    .value_counts()

)

print("\nMissing VALUE by geography:")

print(

    missing_value_rows["GEO"]

    .value_counts()

)

Rows with missing VALUE: 10319

Missing VALUE by status:
STATUS
x     8980
F      783
..     556
Name: count, dtype: int64

Missing VALUE by sales type:
Sales
Total retail sales    10319
Name: count, dtype: int64

Missing VALUE by adjustment:
Adjustments
Unadjusted    10319
Name: count, dtype: int64

Missing VALUE by geography:
GEO
Nunavut                        2852
Northwest Territories          2368
Yukon                          2144
Prince Edward Island            894
Newfoundland and Labrador       484
Ottawa, Ontario                 246
Nova Scotia                     196
Edmonton, Alberta               181
New Brunswick                   176
Quebec, Quebec                  165
Gatineau, Quebec                158
Winnipeg, Manitoba              116
Saskatchewan                     91
Vancouver, British Columbia      83
Manitoba                         51
Calgary, Alberta                 50
Toronto, Ontario                 45
Quebec                            8
British Columbia                  6
Montréal, Quebec                  5
Name: count, dtype: int64

In [9]:
df_clean = df.copy()

print("Original shape:", df.shape)

print("Working copy shape:", df_clean.shape)

Original shape: (79434, 17)
Working copy shape: (79434, 17)

In [11]:
df_clean = df_clean.rename(columns={

    "REF_DATE": "date",

    "GEO": "geography",

    "DGUID": "dguid",

    "North American Industry Classification System (NAICS)": "industry",

    "Sales": "sales_type",

    "Adjustments": "adjustment",

    "UOM": "unit",

    "SCALAR_FACTOR": "scalar_factor",

    "VALUE": "sales_value",

    "STATUS": "status"

})

print(df_clean.columns.tolist())

['date', 'geography', 'dguid', 'industry', 'sales_type', 'adjustment', 'unit', 'UOM_ID', 'scalar_factor', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'sales_value', 'status', 'SYMBOL', 'TERMINATED', 'DECIMALS']

In [15]:
df_clean["date"] = pd.to_datetime(

    df_clean["date"],

    format="%Y-%m"

)

df_clean["year"] = df_clean["date"].dt.year

df_clean["month"] = df_clean["date"].dt.month

print(df_clean["date"].dtype)

print(df_clean["date"].min())

print(df_clean["date"].max())

datetime64[ns]
2017-01-01 00:00:00
2026-06-01 00:00:00

In [17]:
columns_to_drop = [
    "UOM_ID",
    "SCALAR_ID",
    "VECTOR",
    "COORDINATE",
    "SYMBOL",
    "TERMINATED",
    "DECIMALS"
]

df_clean = df_clean.drop(columns=columns_to_drop)

print(df_clean.shape)
print(df_clean.columns.tolist())

(79434, 12)
['date', 'geography', 'dguid', 'industry', 'sales_type', 'adjustment', 'unit', 'scalar_factor', 'sales_value', 'status', 'year', 'month']

In [19]:
print("Before removing missing sales values:", len(df_clean))

df_clean = df_clean.dropna(

    subset=["sales_value"]

).copy()

print("After removing missing sales values:", len(df_clean))

print(

    "Remaining missing sales values:",

    df_clean["sales_value"].isna().sum()

)

Before removing missing sales values: 79434
After removing missing sales values: 69115
Remaining missing sales values: 0

In [21]:
print("Final shape so far:", df_clean.shape)

print("\nMissing values:")

print(df_clean.isnull().sum())

print("\nData types:")

print(df_clean.dtypes)

df_clean.head()

Final shape so far: (69115, 12)

Missing values:
date                 0
geography            0
dguid                0
industry             0
sales_type           0
adjustment           0
unit                 0
scalar_factor        0
sales_value          0
status           39321
year                 0
month                0
dtype: int64

Data types:
date             datetime64[ns]
geography                object
dguid                    object
industry                 object
sales_type               object
adjustment               object
unit                     object
scalar_factor            object
sales_value             float64
status                   object
year                      int32
month                     int32
dtype: object

,date,geography,dguid,industry,sales_type,adjustment,unit,scalar_factor,sales_value,status,year,month
0,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,thousands,41377009.0,NaN,2017,1
1,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,thousands,50417235.0,NaN,2017,1
2,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,thousands,1110045.0,NaN,2017,1
3,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,thousands,1236885.0,NaN,2017,1
4,2017-01-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,thousands,10162441.0,NaN,2017,1

In [23]:
print("Exact duplicate rows:", df_clean.duplicated().sum())

key_columns = [

    "date",

    "geography",

    "industry",

    "sales_type",

    "adjustment"

]

print(

    "Duplicate business keys:",

    df_clean.duplicated(subset=key_columns).sum()

)

print("\nSales types:")

print(df_clean["sales_type"].value_counts())

print("\nAdjustments:")

print(df_clean["adjustment"].value_counts())

print("\nUnits:")

print(df_clean["unit"].value_counts())

print("\nScalar factors:")

print(df_clean["scalar_factor"].value_counts())

Exact duplicate rows: 0
Duplicate business keys: 0

Sales types:
sales_type
Total retail sales         68887
Retail e-commerce sales      228
Name: count, dtype: int64

Adjustments:
adjustment
Unadjusted             63778
Seasonally adjusted     5337
Name: count, dtype: int64

Units:
unit
Dollars    69115
Name: count, dtype: int64

Scalar factors:
scalar_factor
thousands    69115
Name: count, dtype: int64

In [25]:
ecommerce = df_clean[
    df_clean["sales_type"] == "Retail e-commerce sales"
].copy()

print("E-commerce rows:", len(ecommerce))

print("\nDate range:")
print(ecommerce["date"].min(), "to", ecommerce["date"].max())

print("\nGeographies:")
print(ecommerce["geography"].value_counts())

print("\nIndustries:")
print(ecommerce["industry"].value_counts())

print("\nAdjustments:")
print(ecommerce["adjustment"].value_counts())

E-commerce rows: 228

Date range:
2017-01-01 00:00:00 to 2026-06-01 00:00:00

Geographies:
geography
Canada    228
Name: count, dtype: int64

Industries:
industry
Retail trade [44-45]    228
Name: count, dtype: int64

Adjustments:
adjustment
Unadjusted             114
Seasonally adjusted    114
Name: count, dtype: int64

In [31]:
df_clean["sales_millions"] = (

    df_clean["sales_value"] / 1000

).round(2)

df_clean["sales_billions"] = (

    df_clean["sales_value"] / 1000000

).round(4)

df_clean[

    [

        "date",

        "geography",

        "industry",

        "sales_type",

        "sales_value",

        "sales_millions",

        "sales_billions"

    ]

].head()

,date,geography,industry,sales_type,sales_value,sales_millions,sales_billions
0,2017-01-01,Canada,Retail trade [44-45],Total retail sales,41377009.0,41377.01,41.3770
1,2017-01-01,Canada,Retail trade [44-45],Total retail sales,50417235.0,50417.24,50.4172
2,2017-01-01,Canada,Retail trade [44-45],Retail e-commerce sales,1110045.0,1110.04,1.1100
3,2017-01-01,Canada,Retail trade [44-45],Retail e-commerce sales,1236885.0,1236.88,1.2369
4,2017-01-01,Canada,Motor vehicle and parts dealers [441],Total retail sales,10162441.0,10162.44,10.1624

In [33]:
print("Number of industries:", df_clean["industry"].nunique())

print("\nIndustries:")

for industry in sorted(df_clean["industry"].unique()):

    print(industry)

Number of industries: 30

Industries:
Automobile dealers [4411]
Automotive parts, accessories and tire retailers [4413]
Beer, wine and liquor retailers [4453]
Building material and garden equipment and supplies dealers [444]
Cannabis retailers [459993]
Clothing and clothing accessories retailers [4581]
Clothing, clothing accessories, shoes, jewellery, luggage and leather goods retailers [458]
Convenience retailers and vending machine operators [44513]
Electronics and appliances retailers [4492]
Floor covering, window treatment and other home furnishing retailers [44912]
Food and beverage retailers [445]
Furniture retailers [44911]
Furniture, floor covering, window treatment and other home furnishings retailers [4491]
Furniture, home furnishings, electronics and appliances retailers [449]
Gasoline stations and fuel vendors [457]
General merchandise retailers [455]
Grocery and convenience retailers [4451]
Health and personal care retailers [456]
Jewellery, luggage and leather goods retailers [4583]
Miscellaneous retailers [459B]
Motor vehicle and parts dealers [441]
New car dealers [44111]
Other motor vehicle dealers [4412]
Retail trade [44-45]
Shoe retailers [4582]
Specialty food retailers [4452]
Sporting goods, hobby, musical instrument, book retailers and news dealers [459A]
Sporting goods, hobby, musical instrument, book, and miscellaneous retailers [459]
Supermarkets and other grocery retailers (except convenience retailers) [44511]
Used car dealers [44112]

In [35]:
print("Number of geographies:", df_clean["geography"].nunique())

print("\nRows by geography:")

print(

    df_clean["geography"]

    .value_counts()

)

Number of geographies: 23

Rows by geography:
geography
Canada                         7026
Ontario                        3513
Alberta                        3513
Montréal, Quebec               3508
British Columbia               3507
Quebec                         3505
Toronto, Ontario               3468
Manitoba                       3462
Vancouver, British Columbia    3430
Saskatchewan                   3422
New Brunswick                  3337
Nova Scotia                    3317
Newfoundland and Labrador      3029
Calgary, Alberta               2650
Prince Edward Island           2619
Winnipeg, Manitoba             2584
Gatineau, Quebec               2542
Quebec, Quebec                 2535
Edmonton, Alberta              2519
Ottawa, Ontario                2454
Yukon                          1369
Northwest Territories          1145
Nunavut                         661
Name: count, dtype: int64

In [37]:
provinces_territories = [

    "Newfoundland and Labrador",

    "Prince Edward Island",

    "Nova Scotia",

    "New Brunswick",

    "Quebec",

    "Ontario",

    "Manitoba",

    "Saskatchewan",

    "Alberta",

    "British Columbia",

    "Yukon",

    "Northwest Territories",

    "Nunavut"

]

df_clean["geography_level"] = "City/CMA"

df_clean.loc[

    df_clean["geography"].isin(provinces_territories),

    "geography_level"

] = "Province/Territory"

df_clean.loc[

    df_clean["geography"] == "Canada",

    "geography_level"

] = "Canada"

print(df_clean["geography_level"].value_counts())

print(

    df_clean[

        ["geography", "geography_level"]

    ].drop_duplicates().sort_values(

        ["geography_level", "geography"]

    )

)

geography_level
Province/Territory    36399
City/CMA              25690
Canada                 7026
Name: count, dtype: int64
                         geography     geography_level
0                           Canada              Canada
13537             Calgary, Alberta            City/CMA
13567            Edmonton, Alberta            City/CMA
13292             Gatineau, Quebec            City/CMA
210               Montréal, Quebec            City/CMA
13384              Ottawa, Ontario            City/CMA
13262               Quebec, Quebec            City/CMA
270               Toronto, Ontario            City/CMA
420    Vancouver, British Columbia            City/CMA
13445           Winnipeg, Manitoba            City/CMA
360                        Alberta  Province/Territory
390               British Columbia  Province/Territory
300                       Manitoba  Province/Territory
150                  New Brunswick  Province/Territory
60       Newfoundland and Labrador  Province/Territory
480          Northwest Territories  Province/Territory
120                    Nova Scotia  Province/Territory
510                        Nunavut  Province/Territory
240                        Ontario  Province/Territory
90            Prince Edward Island  Province/Territory
180                         Quebec  Province/Territory
330                   Saskatchewan  Province/Territory
450                          Yukon  Province/Territory

In [39]:
df_clean["naics_code"] = (

    df_clean["industry"]

    .str.extract(r"\[([^\]]+)\]")[0]

)

print(

    df_clean[

        ["industry", "naics_code"]

    ].drop_duplicates().sort_values("naics_code")

)

                                                industry naics_code
0                                   Retail trade [44-45]      44-45
4                  Motor vehicle and parts dealers [441]        441
6                              Automobile dealers [4411]       4411
8                                New car dealers [44111]      44111
10                              Used car dealers [44112]      44112
12                    Other motor vehicle dealers [4412]       4412
14     Automotive parts, accessories and tire retaile...       4413
16     Building material and garden equipment and sup...        444
18                     Food and beverage retailers [445]        445
20              Grocery and convenience retailers [4451]       4451
22     Supermarkets and other grocery retailers (exce...      44511
24     Convenience retailers and vending machine oper...      44513
26                       Specialty food retailers [4452]       4452
28                Beer, wine and liquor retailers [4453]       4453
30     Furniture, home furnishings, electronics and a...        449
32     Furniture, floor covering, window treatment an...       4491
34                           Furniture retailers [44911]      44911
36     Floor covering, window treatment and other hom...      44912
38           Electronics and appliances retailers [4492]       4492
40                   General merchandise retailers [455]        455
42              Health and personal care retailers [456]        456
44              Gasoline stations and fuel vendors [457]        457
46     Clothing, clothing accessories, shoes, jewelle...        458
48     Clothing and clothing accessories retailers [4...       4581
50                                 Shoe retailers [4582]       4582
52     Jewellery, luggage and leather goods retailers...       4583
54     Sporting goods, hobby, musical instrument, boo...        459
11400                        Cannabis retailers [459993]     459993
56     Sporting goods, hobby, musical instrument, boo...       459A
58                        Miscellaneous retailers [459B]       459B

In [41]:
df_clean["status"] = df_clean["status"].fillna("No flag")

print(df_clean["status"].value_counts(dropna=False))

print("\nMissing status values:")

print(df_clean["status"].isna().sum())

status
No flag    39321
A          16862
B           6307
C           4134
D           1803
E            688
Name: count, dtype: int64

Missing status values:
0

In [43]:
print("Final shape:", df_clean.shape)

print("\nMissing values:")

print(df_clean.isnull().sum())

print("\nExact duplicate rows:")

print(df_clean.duplicated().sum())

print("\nDate range:")

print(df_clean["date"].min(), "to", df_clean["date"].max())

print("\nGeographies:", df_clean["geography"].nunique())

print("Industries:", df_clean["industry"].nunique())

print("\nSales types:")

print(df_clean["sales_type"].value_counts())

print("\nGeography levels:")

print(df_clean["geography_level"].value_counts())

print("\nFinal columns:")

print(df_clean.columns.tolist())

Final shape: (69115, 16)

Missing values:
date               0
geography          0
dguid              0
industry           0
sales_type         0
adjustment         0
unit               0
scalar_factor      0
sales_value        0
status             0
year               0
month              0
sales_millions     0
sales_billions     0
geography_level    0
naics_code         0
dtype: int64

Exact duplicate rows:
0

Date range:
2017-01-01 00:00:00 to 2026-06-01 00:00:00

Geographies: 23
Industries: 30

Sales types:
sales_type
Total retail sales         68887
Retail e-commerce sales      228
Name: count, dtype: int64

Geography levels:
geography_level
Province/Territory    36399
City/CMA              25690
Canada                 7026
Name: count, dtype: int64

Final columns:
['date', 'geography', 'dguid', 'industry', 'sales_type', 'adjustment', 'unit', 'scalar_factor', 'sales_value', 'status', 'year', 'month', 'sales_millions', 'sales_billions', 'geography_level', 'naics_code']

In [45]:
output_path = "/Users/yuanquan0901/Desktop/BSMM 8730/group project/retail_sales_clean.csv"

df_clean.to_csv(

    output_path,

    index=False,

    encoding="utf-8-sig"

)

print("Saved to:")

print(output_path)

Saved to:
/Users/yuanquan0901/Desktop/BSMM 8730/group project/retail_sales_clean.csv

In [47]:
import pandas as pd

check = pd.read_csv(

    "/Users/yuanquan0901/Desktop/BSMM 8730/group project/retail_sales_clean.csv"

)

print("Shape:", check.shape)

print("Columns:", len(check.columns))

print("Duplicate rows:", check.duplicated().sum())

print("Missing values:", check.isnull().sum().sum())

check.head()

Shape: (69115, 16)
Columns: 16
Duplicate rows: 0
Missing values: 0

,date,geography,dguid,industry,sales_type,adjustment,unit,scalar_factor,sales_value,status,year,month,sales_millions,sales_billions,geography_level,naics_code
0,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,thousands,41377009.0,No flag,2017,1,41377.01,41.3770,Canada,44-45
1,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,thousands,50417235.0,No flag,2017,1,50417.24,50.4172,Canada,44-45
2,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,thousands,1110045.0,No flag,2017,1,1110.04,1.1100,Canada,44-45
3,2017-01-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,thousands,1236885.0,No flag,2017,1,1236.88,1.2369,Canada,44-45
4,2017-01-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,thousands,10162441.0,No flag,2017,1,10162.44,10.1624,Canada,441