In [1]:
import json

import pandas as pd

import os

file_path = "/Users/yuanquan0901/Desktop/BSMM 8730/group project/ind-econ_(semi-structured data).json"

with open(file_path, "r", encoding="utf-8") as f:

    data = json.load(f)

print("JSON loaded successfully")

print(type(data))

print(data.keys())

JSON loaded successfully
<class 'dict'>
dict_keys(['results'])

In [3]:
print(type(data["results"]))

print("\nKeys inside results:")

print(data["results"].keys())

<class 'dict'>

Keys inside results:
dict_keys(['geo', 'themes_en', 'themes_fr', 'indicators'])

In [5]:
indicators = data["results"]["indicators"]

print("Type:", type(indicators))

print("Number of indicators:", len(indicators))

print("\nFirst indicator:")

print(indicators[0])

Type: <class 'list'>
Number of indicators: 230

First indicator:
{'registry_number': 3569, 'indicator_number': 1, 'geo_code': 0, 'title': {'en': 'Real GDP by industry', 'fr': 'PIB réel par industrie'}, 'value': {'en': '', 'fr': ''}, 'refper': {'en': 'July 2026', 'fr': 'Juillet 2026'}, 'daily_url': {'en': '/daily-quotidien/260929/dq260929a-eng.htm', 'fr': '/daily-quotidien/260929/dq260929a-fra.htm'}, 'daily_title': {'en': 'Gross domestic product by industry', 'fr': 'Produit intérieur brut par industrie'}, 'source': '36100434', 'themes': '*3605**360504**4510**451003*', 'release_date': '2026-09-29', 'growth_rate': {'growth': {'en': '0.0%', 'fr': '0,0 %'}, 'arrow_direction': 0, 'details': {'en': '(monthly change)', 'fr': '(variation mensuelle)'}}}

In [7]:
df_json = pd.json_normalize(indicators)

print("Shape:", df_json.shape)

print("\nColumns:")

for column in df_json.columns:

    print(column)

Shape: (230, 22)

Columns:
registry_number
indicator_number
geo_code
source
themes
release_date
title.en
title.fr
value.en
value.fr
refper.en
refper.fr
daily_url.en
daily_url.fr
daily_title.en
daily_title.fr
growth_rate.growth.en
growth_rate.growth.fr
growth_rate.arrow_direction
growth_rate.details.en
growth_rate.details.fr
growth_rate

In [9]:
indicator_list = df_json[

    [

        "indicator_number",

        "geo_code",

        "title.en",

        "value.en",

        "refper.en",

        "source",

        "release_date",

        "growth_rate.growth.en",

        "growth_rate.details.en"

    ]

].copy()

pd.set_option("display.max_rows", 250)

pd.set_option("display.max_colwidth", 100)

indicator_list

,indicator_number,geo_code,title.en,value.en,refper.en,source,release_date,growth_rate.growth.en,growth_rate.details.en
0,1,0,Real GDP by industry,,July 2026,36100434,2026-09-29,0.0%,(monthly change)
1,1,0,Tourism spending in Canada,$28.5 billion,Second quarter 2026,36100230,2026-09-25,0.3%,(quarterly change)
2,2,0,Domestic tourism spending,$21.2 billion,Second quarter 2026,36100230,2026-09-25,0.0%,(quarterly change)
3,3,0,Tourism spending by non-residents,$7.3 billion,Second quarter 2026,36100230,2026-09-25,1.0%,(quarterly change)
4,4,0,Tourism share of gross domestic product,1.77%,Second quarter 2026,36100235,2026-09-25,NaN,NaN
5,6,0,Jobs generated by tourism,"699,000",Second quarter 2026,36100232,2026-09-25,0.4%,(quarterly change)
6,1,10,Retail sales,$9.8 billion,July 2026,20100056,2026-09-24,-1.4%,(monthly change)
7,1,9,Retail sales,$9.7 billion,July 2026,20100056,2026-09-24,1.4%,(monthly change)
8,1,12,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,2.6%,(monthly change)
9,1,13,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,-3.6%,(monthly change)
10,1,0,Average weekly earnings,"$1,347.14",July 2026,14100223,2026-09-24,3.2%,(12-month change)
11,1,11,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,1.6%,(monthly change)
12,1,7,Retail sales,$2.5 billion,July 2026,20100056,2026-09-24,-0.4%,(monthly change)
13,1,13,Average weekly earnings,"$1,844.70",July 2026,14100223,2026-09-24,2.3%,(12-month change)
14,1,12,Average weekly earnings,"$1,821.38",July 2026,14100223,2026-09-24,4.8%,(12-month change)
15,1,11,Average weekly earnings,"$1,504.26",July 2026,14100223,2026-09-24,1.1%,(12-month change)
16,1,10,Average weekly earnings,"$1,356.78",July 2026,14100223,2026-09-24,4.4%,(12-month change)
17,1,9,Average weekly earnings,"$1,399.61",July 2026,14100223,2026-09-24,2.5%,(12-month change)
18,1,0,Retail sales,$73.7 billion,July 2026,20100056,2026-09-24,-0.7%,(monthly change)
19,1,1,Retail sales,$1.1 billion,July 2026,20100056,2026-09-24,-1.5%,(monthly change)
20,1,2,Retail sales,$0.3 billion,July 2026,20100056,2026-09-24,0.2%,(monthly change)
21,1,3,Retail sales,$2.0 billion,July 2026,20100056,2026-09-24,0.6%,(monthly change)
22,1,4,Retail sales,$1.6 billion,July 2026,20100056,2026-09-24,1.6%,(monthly change)
23,1,5,Retail sales,$16.2 billion,July 2026,20100056,2026-09-24,-0.0%,(monthly change)
24,1,6,Retail sales,$27.9 billion,July 2026,20100056,2026-09-24,-2.0%,(monthly change)
25,1,8,Retail sales,$2.3 billion,July 2026,20100056,2026-09-24,0.5%,(monthly change)
26,1,1,Average weekly earnings,"$1,317.98",July 2026,14100223,2026-09-24,1.7%,(12-month change)
27,1,2,Average weekly earnings,"$1,207.99",July 2026,14100223,2026-09-24,4.1%,(12-month change)
28,1,3,Average weekly earnings,"$1,228.91",July 2026,14100223,2026-09-24,5.6%,(12-month change)
29,1,4,Average weekly earnings,"$1,261.88",July 2026,14100223,2026-09-24,5.3%,(12-month change)
30,1,5,Average weekly earnings,"$1,279.96",July 2026,14100223,2026-09-24,1.9%,(12-month change)
31,1,6,Average weekly earnings,"$1,391.19",July 2026,14100223,2026-09-24,3.6%,(12-month change)
32,1,7,Average weekly earnings,"$1,217.11",July 2026,14100223,2026-09-24,3.1%,(12-month change)
33,1,8,Average weekly earnings,"$1,325.24",July 2026,14100223,2026-09-24,4.4%,(12-month change)
34,6,0,Non-resident visitors entering Canada (seasonally adjusted data),"2,628,275",July 2026,24100054,2026-09-22,1.2%,(monthly change)
35,7,0,Canadian residents returning to Canada from abroad (seasonally adjusted data),"3,683,821",July 2026,24100054,2026-09-22,-0.3%,(monthly change)
36,8,0,Non-resident visitors entering Canada (unadjusted data),"4,584,611",July 2026,24100053,2026-09-22,7.9%,(12-month change)
37,9,0,Canadian residents returning to Canada from abroad (unadjusted data),"3,859,908",July 2026,24100053,2026-09-22,6.9%,(12-month change)
38,1,0,Total investment in building construction,$23.6 billion,July 2026,34100293,2026-09-21,1.2%,(monthly change)
39,1,0,Foreign investment in Canadian securities,$20.7 billion,July 2026,36100028,2026-09-17,NaN,NaN
40,1,0,Industrial Product Price Index,,August 2026,18100265,2026-09-17,1.3%,(monthly change)
41,2,0,Canadian investment in foreign securities,-$30.6 billion,July 2026,36100028,2026-09-17,NaN,NaN
42,2,0,"Industrial Product Price Index, excluding energy and petroleum products",,August 2026,18100265,2026-09-17,0.8%,(monthly change)
43,3,0,Raw Materials Price Index,,August 2026,18100268,2026-09-17,3.1%,(monthly change)
44,4,0,"Raw Materials Price Index, excluding crude energy products",,August 2026,18100268,2026-09-17,1.1%,(monthly change)
45,1,0,Total wheat production,36.1 million tonnes,2026,32100359,2026-09-16,-10.9%,(year-over-year change)
46,1,3,Building permits,$0.2 billion,July 2026,34100292,2026-09-16,-9.6%,(monthly change)
47,1,5,Building permits,$2.7 billion,July 2026,34100292,2026-09-16,-8.4%,(monthly change)
48,1,0,Building permits,$12.2 billion,July 2026,34100292,2026-09-16,-17.3%,(monthly change)
49,1,1,Building permits,$0.1 billion,July 2026,34100292,2026-09-16,-13.8%,(monthly change)
50,1,2,Building permits,$0.1 billion,July 2026,34100292,2026-09-16,-35.8%,(monthly change)
51,1,4,Building permits,$0.3 billion,July 2026,34100292,2026-09-16,65.7%,(monthly change)
52,1,6,Building permits,$4.6 billion,July 2026,34100292,2026-09-16,-25.2%,(monthly change)
53,1,7,Building permits,$0.4 billion,July 2026,34100292,2026-09-16,-23.9%,(monthly change)
54,1,8,Building permits,$0.3 billion,July 2026,34100292,2026-09-16,-48.4%,(monthly change)
55,1,9,Building permits,$1.6 billion,July 2026,34100292,2026-09-16,-13.9%,(monthly change)
56,1,10,Building permits,$1.9 billion,July 2026,34100292,2026-09-16,-11.5%,(monthly change)
57,2,0,Total canola production,22.1 million tonnes,2026,32100359,2026-09-16,-0.8%,(year-over-year change)
58,3,0,Total soybeans production,7.5 million tonnes,2026,32100359,2026-09-16,7.8%,(year-over-year change)
59,4,0,Total corn for grain production,16.5 million tonnes,2026,32100359,2026-09-16,11.3%,(year-over-year change)
60,1,11,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$21.9 million,July 2026,20100074,2026-09-15,-11.7%,(monthly change)
61,1,12,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$26.8 million,July 2026,20100074,2026-09-15,-1.7%,(monthly change)
62,1,10,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$9,008.8 million",July 2026,20100074,2026-09-15,4.9%,(monthly change)
63,1,9,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$10,320.6 million",July 2026,20100074,2026-09-15,-1.0%,(monthly change)
64,1,8,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$4,216.8 million",July 2026,20100074,2026-09-15,0.4%,(monthly change)
65,1,7,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$2,159.0 million",July 2026,20100074,2026-09-15,0.7%,(monthly change)
66,1,6,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$48,720.2 million",July 2026,20100074,2026-09-15,1.0%,(monthly change)
67,1,5,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$15,656.0 million",July 2026,20100074,2026-09-15,-2.8%,(monthly change)
68,1,3,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...","$1,366.7 million",July 2026,20100074,2026-09-15,-2.8%,(monthly change)
69,1,2,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$127.3 million,July 2026,20100074,2026-09-15,2.0%,(monthly change)
70,1,1,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$532.9 million,July 2026,20100074,2026-09-15,-8.2%,(monthly change)
71,1,0,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$93.1 billion,July 2026,20100074,2026-09-15,0.3%,(monthly change)
72,1,13,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$9.4 million,July 2026,20100074,2026-09-15,-30.6%,(monthly change)
73,1,4,"Wholesale sales (excluding petroleum, petroleum products, and other hydrocarbons and excluding o...",$925.0 million,July 2026,20100074,2026-09-15,0.9%,(monthly change)
74,1,0,Manufacturing sales,$78.7 billion,July 2026,16100047,2026-09-14,-0.4%,(monthly change)
75,1,0,Consumer Price Index,,August 2026,18100004,2026-09-14,3.0%,(12-month change)
76,2,0,Inventories,$127.5 billion,July 2026,16100047,2026-09-14,0.3%,(monthly change)
77,2,0,Food purchased from stores,,August 2026,18100004,2026-09-14,2.8%,(12-month change)
78,3,0,Shelter,,August 2026,18100004,2026-09-14,1.5%,(12-month change)
79,3,0,Inventory-to-sales ratio,1.62,July 2026,16100047,2026-09-14,0.01 pts,(monthly change)
80,4,0,Transportation,,August 2026,18100004,2026-09-14,7.5%,(12-month change)
81,4,0,Unfilled orders,$134.6 billion,July 2026,16100047,2026-09-14,1.9%,(monthly change)
82,2,0,National net worth,$20.3 trillion,Second quarter 2026,36100580,2026-09-11,5.8%,(quarterly change)
83,3,0,Debt service ratio,14.52%,Second quarter 2026,11100065,2026-09-11,-0.16,(quarterly change)
84,4,0,Household credit market debt - financial flow (seasonally adjusted),$29.4 billion,Second quarter 2026,38100238,2026-09-11,-$5.0 billion,(quarterly change)
85,5,0,Household net worth,$19.1 trillion,Second quarter 2026,36100580,2026-09-11,2.9%,(quarterly change)
86,1,0,Canada’s net international investment position,"$1,945.5 billion",Second quarter 2026,36100485,2026-09-10,NaN,NaN
87,1,0,Wheat stocks,6.6 million tonnes,July 2026,32100007,2026-09-09,56.8%,(year-over-year change)
88,2,0,Canola stocks,1.9 million tonnes,July 2026,32100007,2026-09-09,18.9%,(year-over-year change)
89,1,2,Employment level,"96,000",August 2026,14100287,2026-09-04,-0.4%,(monthly change)
90,1,3,Employment level,"541,000",August 2026,14100287,2026-09-04,0.5%,(monthly change)
91,1,4,Employment level,"409,000",August 2026,14100287,2026-09-04,0.6%,(monthly change)
92,1,5,Employment level,"4,589,000",August 2026,14100287,2026-09-04,-0.4%,(monthly change)
93,1,6,Employment level,"8,307,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
94,1,7,Employment level,"756,000",August 2026,14100287,2026-09-04,0.1%,(monthly change)
95,1,8,Employment level,"622,000",August 2026,14100287,2026-09-04,0.4%,(monthly change)
96,1,9,Employment level,"2,661,000",August 2026,14100287,2026-09-04,-0.3%,(monthly change)
97,1,0,Employment level,"21,173,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
98,1,1,Employment level,"245,000",August 2026,14100287,2026-09-04,0.6%,(monthly change)
99,1,10,Employment level,"2,949,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
100,2,6,Unemployment rate,6.9%,August 2026,14100287,2026-09-04,0.1 pts,(monthly change)
101,2,8,Unemployment rate,6.0%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
102,2,9,Unemployment rate,6.8%,August 2026,14100287,2026-09-04,-0.2 pts,(monthly change)
103,2,10,Unemployment rate,6.5%,August 2026,14100287,2026-09-04,0.3 pts,(monthly change)
104,2,7,Unemployment rate,5.0%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
105,2,0,Unemployment rate,6.4%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
106,2,1,Unemployment rate,8.6%,August 2026,14100287,2026-09-04,-0.7 pts,(monthly change)
107,2,2,Unemployment rate,7.9%,August 2026,14100287,2026-09-04,1.1 pts,(monthly change)
108,2,3,Unemployment rate,6.1%,August 2026,14100287,2026-09-04,-0.1 pts,(monthly change)
109,2,4,Unemployment rate,7.3%,August 2026,14100287,2026-09-04,0.3 pts,(monthly change)
110,2,5,Unemployment rate,5.6%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
111,1,0,Imports of goods,$75.4 billion,July 2026,12100011,2026-09-03,2.2%,(monthly change)
112,1,0,Quarterly labour productivity,,Second quarter 2026,36100206,2026-09-03,1.0%,(quarterly change)
113,2,0,Exports of goods,$76.1 billion,July 2026,12100011,2026-09-03,-2.3%,(monthly change)
114,3,0,Goods trade balance,$769 million,July 2026,12100011,2026-09-03,NaN,NaN
115,1,0,Real GDP by expenditure,,Second quarter 2026,36100104,2026-08-28,0.8%,(quarterly change)
116,2,0,Household saving rate,3.7%,Second quarter 2026,36100112,2026-08-28,NaN,NaN
117,3,0,Household disposable income,,Second quarter 2026,36100112,2026-08-28,2.1%,(quarterly change)
118,4,0,Terms of trade,"110.8 <span class=""sd-indicator-value-details"">(2017=100)</span>",Second quarter 2026,36100105,2026-08-28,NaN,NaN
119,1,0,Current account balance,$8.8 billion,Second quarter 2026,36100018,2026-08-27,NaN,NaN
120,1,0,"Canadian corporations' operating profit, seasonally adjusted",$228.2 billion,Second quarter 2026,33100226,2026-08-24,NaN,NaN
121,1,0,Wheat area,25.3 million acres,2026,32100359,2026-06-30,-5.9%,(annual change)
122,2,0,Canola area,23.4 million acres,2026,32100359,2026-06-30,8.4%,(annual change)
123,3,0,Soybean area,6.0 million acres,2026,32100359,2026-06-30,3.1%,(annual change)
124,4,0,Corn for grain area,4.0 million acres,2026,32100359,2026-06-30,4.8%,(annual change)
125,1,1,Realized net farm income,-$5.2 million,2025,32100052,2026-05-27,-19.5%,(annual change)
126,1,10,Realized net farm income,-$318.8 million,2025,32100052,2026-05-27,19.7%,(annual change)
127,1,0,Realized net farm income,$8.3 billion,2025,32100052,2026-05-27,-0.3%,(annual change)
128,1,9,Realized net farm income,"$1,960.5 million",2025,32100052,2026-05-27,-14.3%,(annual change)
129,1,8,Realized net farm income,"$2,936.1 million",2025,32100052,2026-05-27,-26.1%,(annual change)
130,1,7,Realized net farm income,"$1,482.7 million",2025,32100052,2026-05-27,25.9%,(annual change)
131,1,6,Realized net farm income,"$2,004.1 million",2025,32100052,2026-05-27,42.8%,(annual change)
132,1,5,Realized net farm income,$318.9 million,2025,32100052,2026-05-27,305.2%,(annual change)
133,1,4,Realized net farm income,-$96.1 million,2025,32100052,2026-05-27,-506.8%,(annual change)
134,1,3,Realized net farm income,-$14.2 million,2025,32100052,2026-05-27,73.4%,(annual change)
135,1,2,Realized net farm income,$71.5 million,2025,32100052,2026-05-27,-34.2%,(annual change)
136,2,3,Farm cash receipts,$824.1 million,2025,32100045,2026-05-27,7.2%,(annual change)
137,2,5,Farm cash receipts,"$13,543.1 million",2025,32100045,2026-05-27,4.5%,(annual change)
138,2,6,Farm cash receipts,"$24,086.5 million",2025,32100045,2026-05-27,8.0%,(annual change)
139,2,7,Farm cash receipts,"$10,332.4 million",2025,32100045,2026-05-27,6.0%,(annual change)
140,2,8,Farm cash receipts,"$21,076.6 million",2025,32100045,2026-05-27,-1.8%,(annual change)
141,2,4,Farm cash receipts,"$1,303.4 million",2025,32100045,2026-05-27,10.1%,(annual change)
142,2,1,Farm cash receipts,$170.4 million,2025,32100045,2026-05-27,0.7%,(annual change)
143,2,9,Farm cash receipts,"$24,483.0 million",2025,32100045,2026-05-27,5.9%,(annual change)
144,2,10,Farm cash receipts,"$5,505.2 million",2025,32100045,2026-05-27,9.0%,(annual change)
145,2,0,Farm cash receipts,$102.2 billion,2025,32100045,2026-05-27,4.7%,(annual change)
146,2,2,Farm cash receipts,$835.0 million,2025,32100045,2026-05-27,-0.7%,(annual change)
147,3,2,Farm operating expenses,$683.8 million,2025,32100049,2026-05-27,4.2%,(annual change)
148,3,5,Farm operating expenses,"$11,728.4 million",2025,32100049,2026-05-27,0.4%,(annual change)
149,3,6,Farm operating expenses,"$19,437.4 million",2025,32100049,2026-05-27,5.6%,(annual change)
150,3,0,Farm operating expenses,$83.0 billion,2025,32100049,2026-05-27,5.1%,(annual change)
151,3,1,Farm operating expenses,$158.5 million,2025,32100049,2026-05-27,1.2%,(annual change)
152,3,8,Farm operating expenses,"$15,898.0 million",2025,32100049,2026-05-27,3.5%,(annual change)
153,3,7,Farm operating expenses,"$7,910.2 million",2025,32100049,2026-05-27,3.0%,(annual change)
154,3,3,Farm operating expenses,$744.4 million,2025,32100049,2026-05-27,1.8%,(annual change)
155,3,4,Farm operating expenses,"$1,299.5 million",2025,32100049,2026-05-27,22.1%,(annual change)
156,3,10,Farm operating expenses,"$5,223.1 million",2025,32100049,2026-05-27,7.4%,(annual change)
157,3,9,Farm operating expenses,"$19,949.6 million",2025,32100049,2026-05-27,8.4%,(annual change)
158,4,6,Total net farm income,"$1,600.4 million",2025,32100052,2026-05-27,$182.5 million,(annual change)
159,4,8,Total net farm income,"$5,643.8 million",2025,32100052,2026-05-27,"$1,378.4 million",(annual change)
160,4,0,Total net farm income,$12.7 billion,2025,32100052,2026-05-27,$4.3 billion,(annual change)
161,4,5,Total net farm income,$154.9 million,2025,32100052,2026-05-27,$184.2 million,(annual change)
162,4,4,Total net farm income,-$91.9 million,2025,32100052,2026-05-27,-$165.8 million,(annual change)
163,4,7,Total net farm income,"$1,556.4 million",2025,32100052,2026-05-27,$410.3 million,(annual change)
164,4,1,Total net farm income,-$5.5 million,2025,32100052,2026-05-27,-$0.5 million,(annual change)
165,4,2,Total net farm income,$22.5 million,2025,32100052,2026-05-27,-$75.0 million,(annual change)
166,4,3,Total net farm income,-$16.9 million,2025,32100052,2026-05-27,$36.2 million,(annual change)
167,4,10,Total net farm income,-$156.4 million,2025,32100052,2026-05-27,$238.8 million,(annual change)
168,4,9,Total net farm income,"$4,036.8 million",2025,32100052,2026-05-27,"$2,157.7 million",(annual change)
169,1,9,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.7%,(annual change)
170,1,10,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.0%,(annual change)
171,1,5,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,0.6%,(annual change)
172,1,4,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.0%,(annual change)
173,1,3,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.3%,(annual change)
174,1,2,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.8%,(annual change)
175,1,6,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,1.3%,(annual change)
176,1,8,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,2.2%,(annual change)
177,1,7,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,1.3%,(annual change)
178,1,11,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,0.6%,(annual change)
179,1,13,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,0.1%,(annual change)
180,1,1,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,3.5%,(annual change)
181,1,0,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,1.6%,(annual change)
182,1,12,Annual real gross domestic product by industry,,2025,36100711,2026-05-01,-2.0%,(annual change)
183,1,11,Capital expenditures: Non-residential construction,$760.2 million,2026,34100035,2026-02-25,17.0%,(annual change)
184,1,10,Capital expenditures: Non-residential construction,"$47,410.4 million",2026,34100035,2026-02-25,-0.2%,(annual change)
185,1,13,Capital expenditures: Non-residential construction,"$1,558.1 million",2026,34100035,2026-02-25,-19.9%,(annual change)
186,1,12,Capital expenditures: Non-residential construction,$902.8 million,2026,34100035,2026-02-25,15.1%,(annual change)
187,1,6,Capital expenditures: Non-residential construction,"$84,792.1 million",2026,34100035,2026-02-25,12.3%,(annual change)
188,1,7,Capital expenditures: Non-residential construction,"$6,424.4 million",2026,34100035,2026-02-25,-3.6%,(annual change)
189,1,9,Capital expenditures: Non-residential construction,"$60,896.6 million",2026,34100035,2026-02-25,8.8%,(annual change)

In [11]:
keywords = [

    "retail",

    "earnings",

    "consumer",

    "price",

    "employment",

    "unemployment",

    "population",

    "GDP"

]

pattern = "|".join(keywords)

relevant = indicator_list[

    indicator_list["title.en"].str.contains(

        pattern,

        case=False,

        na=False

    )

]

print("Potentially relevant indicators:", len(relevant))

relevant

Potentially relevant indicators: 57

,indicator_number,geo_code,title.en,value.en,refper.en,source,release_date,growth_rate.growth.en,growth_rate.details.en
0,1,0,Real GDP by industry,,July 2026,36100434,2026-09-29,0.0%,(monthly change)
6,1,10,Retail sales,$9.8 billion,July 2026,20100056,2026-09-24,-1.4%,(monthly change)
7,1,9,Retail sales,$9.7 billion,July 2026,20100056,2026-09-24,1.4%,(monthly change)
8,1,12,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,2.6%,(monthly change)
9,1,13,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,-3.6%,(monthly change)
10,1,0,Average weekly earnings,"$1,347.14",July 2026,14100223,2026-09-24,3.2%,(12-month change)
11,1,11,Retail sales,$0.1 billion,July 2026,20100056,2026-09-24,1.6%,(monthly change)
12,1,7,Retail sales,$2.5 billion,July 2026,20100056,2026-09-24,-0.4%,(monthly change)
13,1,13,Average weekly earnings,"$1,844.70",July 2026,14100223,2026-09-24,2.3%,(12-month change)
14,1,12,Average weekly earnings,"$1,821.38",July 2026,14100223,2026-09-24,4.8%,(12-month change)
15,1,11,Average weekly earnings,"$1,504.26",July 2026,14100223,2026-09-24,1.1%,(12-month change)
16,1,10,Average weekly earnings,"$1,356.78",July 2026,14100223,2026-09-24,4.4%,(12-month change)
17,1,9,Average weekly earnings,"$1,399.61",July 2026,14100223,2026-09-24,2.5%,(12-month change)
18,1,0,Retail sales,$73.7 billion,July 2026,20100056,2026-09-24,-0.7%,(monthly change)
19,1,1,Retail sales,$1.1 billion,July 2026,20100056,2026-09-24,-1.5%,(monthly change)
20,1,2,Retail sales,$0.3 billion,July 2026,20100056,2026-09-24,0.2%,(monthly change)
21,1,3,Retail sales,$2.0 billion,July 2026,20100056,2026-09-24,0.6%,(monthly change)
22,1,4,Retail sales,$1.6 billion,July 2026,20100056,2026-09-24,1.6%,(monthly change)
23,1,5,Retail sales,$16.2 billion,July 2026,20100056,2026-09-24,-0.0%,(monthly change)
24,1,6,Retail sales,$27.9 billion,July 2026,20100056,2026-09-24,-2.0%,(monthly change)
25,1,8,Retail sales,$2.3 billion,July 2026,20100056,2026-09-24,0.5%,(monthly change)
26,1,1,Average weekly earnings,"$1,317.98",July 2026,14100223,2026-09-24,1.7%,(12-month change)
27,1,2,Average weekly earnings,"$1,207.99",July 2026,14100223,2026-09-24,4.1%,(12-month change)
28,1,3,Average weekly earnings,"$1,228.91",July 2026,14100223,2026-09-24,5.6%,(12-month change)
29,1,4,Average weekly earnings,"$1,261.88",July 2026,14100223,2026-09-24,5.3%,(12-month change)
30,1,5,Average weekly earnings,"$1,279.96",July 2026,14100223,2026-09-24,1.9%,(12-month change)
31,1,6,Average weekly earnings,"$1,391.19",July 2026,14100223,2026-09-24,3.6%,(12-month change)
32,1,7,Average weekly earnings,"$1,217.11",July 2026,14100223,2026-09-24,3.1%,(12-month change)
33,1,8,Average weekly earnings,"$1,325.24",July 2026,14100223,2026-09-24,4.4%,(12-month change)
40,1,0,Industrial Product Price Index,,August 2026,18100265,2026-09-17,1.3%,(monthly change)
42,2,0,"Industrial Product Price Index, excluding energy and petroleum products",,August 2026,18100265,2026-09-17,0.8%,(monthly change)
43,3,0,Raw Materials Price Index,,August 2026,18100268,2026-09-17,3.1%,(monthly change)
44,4,0,"Raw Materials Price Index, excluding crude energy products",,August 2026,18100268,2026-09-17,1.1%,(monthly change)
75,1,0,Consumer Price Index,,August 2026,18100004,2026-09-14,3.0%,(12-month change)
89,1,2,Employment level,"96,000",August 2026,14100287,2026-09-04,-0.4%,(monthly change)
90,1,3,Employment level,"541,000",August 2026,14100287,2026-09-04,0.5%,(monthly change)
91,1,4,Employment level,"409,000",August 2026,14100287,2026-09-04,0.6%,(monthly change)
92,1,5,Employment level,"4,589,000",August 2026,14100287,2026-09-04,-0.4%,(monthly change)
93,1,6,Employment level,"8,307,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
94,1,7,Employment level,"756,000",August 2026,14100287,2026-09-04,0.1%,(monthly change)
95,1,8,Employment level,"622,000",August 2026,14100287,2026-09-04,0.4%,(monthly change)
96,1,9,Employment level,"2,661,000",August 2026,14100287,2026-09-04,-0.3%,(monthly change)
97,1,0,Employment level,"21,173,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
98,1,1,Employment level,"245,000",August 2026,14100287,2026-09-04,0.6%,(monthly change)
99,1,10,Employment level,"2,949,000",August 2026,14100287,2026-09-04,-0.2%,(monthly change)
100,2,6,Unemployment rate,6.9%,August 2026,14100287,2026-09-04,0.1 pts,(monthly change)
101,2,8,Unemployment rate,6.0%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
102,2,9,Unemployment rate,6.8%,August 2026,14100287,2026-09-04,-0.2 pts,(monthly change)
103,2,10,Unemployment rate,6.5%,August 2026,14100287,2026-09-04,0.3 pts,(monthly change)
104,2,7,Unemployment rate,5.0%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
105,2,0,Unemployment rate,6.4%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
106,2,1,Unemployment rate,8.6%,August 2026,14100287,2026-09-04,-0.7 pts,(monthly change)
107,2,2,Unemployment rate,7.9%,August 2026,14100287,2026-09-04,1.1 pts,(monthly change)
108,2,3,Unemployment rate,6.1%,August 2026,14100287,2026-09-04,-0.1 pts,(monthly change)
109,2,4,Unemployment rate,7.3%,August 2026,14100287,2026-09-04,0.3 pts,(monthly change)
110,2,5,Unemployment rate,5.6%,August 2026,14100287,2026-09-04,0.0 pts,(monthly change)
115,1,0,Real GDP by expenditure,,Second quarter 2026,36100104,2026-08-28,0.8%,(quarterly change)

In [13]:
selected_indicators = [

    "Average weekly earnings",

    "Consumer Price Index",

    "Employment level",

    "Unemployment rate",

    "Real GDP by expenditure"

]

df_econ = df_json[

    df_json["title.en"].isin(selected_indicators)

].copy()

print("Rows selected:", len(df_econ))

print("\nIndicators:")

print(df_econ["title.en"].value_counts())

df_econ.head()

Rows selected: 38

Indicators:
title.en
Average weekly earnings    14
Employment level           11
Unemployment rate          11
Consumer Price Index        1
Real GDP by expenditure     1
Name: count, dtype: int64

,registry_number,indicator_number,geo_code,source,themes,release_date,title.en,title.fr,value.en,value.fr,...,daily_url.en,daily_url.fr,daily_title.en,daily_title.fr,growth_rate.growth.en,growth_rate.growth.fr,growth_rate.arrow_direction,growth_rate.details.en,growth_rate.details.fr,growth_rate
10,3555,1,0,14100223,*1401**140101**1402**140201**4510**451002*,2026-09-24,Average weekly earnings,Rémunération hebdomadaire moyenne,"$1,347.14","1 347,14 $",...,/daily-quotidien/260924/dq260924b-eng.htm,/daily-quotidien/260924/dq260924b-fra.htm,"Payroll employment, earnings and hours, and job vacancies","Emploi, rémunération et heures de travail, et postes vacants",3.2%,"3,2 %",1.0,(12-month change),(variation sur 12 mois),NaN
13,3555,1,13,14100223,*1401**140101**1402**140201**4510**451002*,2026-09-24,Average weekly earnings,Rémunération hebdomadaire moyenne,"$1,844.70","1 844,70 $",...,/daily-quotidien/260924/dq260924b-eng.htm,/daily-quotidien/260924/dq260924b-fra.htm,"Payroll employment, earnings and hours, and job vacancies","Emploi, rémunération et heures de travail, et postes vacants",2.3%,"2,3 %",1.0,(12-month change),(variation sur 12 mois),NaN
14,3555,1,12,14100223,*1401**140101**1402**140201**4510**451002*,2026-09-24,Average weekly earnings,Rémunération hebdomadaire moyenne,"$1,821.38","1 821,38 $",...,/daily-quotidien/260924/dq260924b-eng.htm,/daily-quotidien/260924/dq260924b-fra.htm,"Payroll employment, earnings and hours, and job vacancies","Emploi, rémunération et heures de travail, et postes vacants",4.8%,"4,8 %",1.0,(12-month change),(variation sur 12 mois),NaN
15,3555,1,11,14100223,*1401**140101**1402**140201**4510**451002*,2026-09-24,Average weekly earnings,Rémunération hebdomadaire moyenne,"$1,504.26","1 504,26 $",...,/daily-quotidien/260924/dq260924b-eng.htm,/daily-quotidien/260924/dq260924b-fra.htm,"Payroll employment, earnings and hours, and job vacancies","Emploi, rémunération et heures de travail, et postes vacants",1.1%,"1,1 %",1.0,(12-month change),(variation sur 12 mois),NaN
16,3555,1,10,14100223,*1401**140101**1402**140201**4510**451002*,2026-09-24,Average weekly earnings,Rémunération hebdomadaire moyenne,"$1,356.78","1 356,78 $",...,/daily-quotidien/260924/dq260924b-eng.htm,/daily-quotidien/260924/dq260924b-fra.htm,"Payroll employment, earnings and hours, and job vacancies","Emploi, rémunération et heures de travail, et postes vacants",4.4%,"4,4 %",1.0,(12-month change),(variation sur 12 mois),NaN

In [15]:
df_econ = df_econ[

    [

        "indicator_number",

        "geo_code",

        "title.en",

        "value.en",

        "refper.en",

        "source",

        "release_date",

        "growth_rate.growth.en",

        "growth_rate.details.en"

    ]

].copy()

df_econ.columns = [

    "indicator_number",

    "geo_code",

    "indicator",

    "value",

    "reference_period",

    "source",

    "release_date",

    "growth_rate",

    "growth_details"

]

print(df_econ.shape)

df_econ.head()

(38, 9)

,indicator_number,geo_code,indicator,value,reference_period,source,release_date,growth_rate,growth_details
10,1,0,Average weekly earnings,"$1,347.14",July 2026,14100223,2026-09-24,3.2%,(12-month change)
13,1,13,Average weekly earnings,"$1,844.70",July 2026,14100223,2026-09-24,2.3%,(12-month change)
14,1,12,Average weekly earnings,"$1,821.38",July 2026,14100223,2026-09-24,4.8%,(12-month change)
15,1,11,Average weekly earnings,"$1,504.26",July 2026,14100223,2026-09-24,1.1%,(12-month change)
16,1,10,Average weekly earnings,"$1,356.78",July 2026,14100223,2026-09-24,4.4%,(12-month change)

In [17]:
geo_data = data["results"]["geo"]

print(type(geo_data))

print("Number of geographies:", len(geo_data))

geo_data[:5]

<class 'list'>
Number of geographies: 14

[{'geo_code': '0', 'label': {'en': 'Canada', 'fr': 'Canada'}},
 {'geo_code': '1',
  'label': {'en': 'Newfoundland and Labrador',
   'fr': 'Terre Neuve et Labrador'}},
 {'geo_code': '2',
  'label': {'en': 'Prince Edward Island', 'fr': 'Île-du-Prince-Edouard'}},
 {'geo_code': '3', 'label': {'en': 'Nova Scotia', 'fr': 'Nouvelle-Écosse'}},
 {'geo_code': '4',
  'label': {'en': 'New Brunswick', 'fr': 'Nouveau-Brunswick'}}]

In [19]:
for item in geo_data[:5]:

    print(item)

{'geo_code': '0', 'label': {'en': 'Canada', 'fr': 'Canada'}}
{'geo_code': '1', 'label': {'en': 'Newfoundland and Labrador', 'fr': 'Terre Neuve et Labrador'}}
{'geo_code': '2', 'label': {'en': 'Prince Edward Island', 'fr': 'Île-du-Prince-Edouard'}}
{'geo_code': '3', 'label': {'en': 'Nova Scotia', 'fr': 'Nouvelle-Écosse'}}
{'geo_code': '4', 'label': {'en': 'New Brunswick', 'fr': 'Nouveau-Brunswick'}}

In [21]:
geo_map = {

    int(item["geo_code"]): item["label"]["en"]

    for item in geo_data

}

print(geo_map)

{0: 'Canada', 1: 'Newfoundland and Labrador', 2: 'Prince Edward Island', 3: 'Nova Scotia', 4: 'New Brunswick', 5: 'Quebec', 6: 'Ontario', 7: 'Manitoba', 8: 'Saskatchewan', 9: 'Alberta', 10: 'British Columbia', 11: 'Yukon', 12: 'Northwest Territories', 13: 'Nunavut'}

In [23]:
df_econ["geography"] = df_econ["geo_code"].map(geo_map)

print(df_econ[["geo_code", "geography"]].drop_duplicates().sort_values("geo_code"))

    geo_code                  geography
10         0                     Canada
26         1  Newfoundland and Labrador
27         2       Prince Edward Island
28         3                Nova Scotia
29         4              New Brunswick
30         5                     Quebec
31         6                    Ontario
32         7                   Manitoba
33         8               Saskatchewan
17         9                    Alberta
16        10           British Columbia
15        11                      Yukon
14        12      Northwest Territories
13        13                    Nunavut

In [25]:
print("Missing geography:", df_econ["geography"].isna().sum())

print("\nRows by geography:")

print(df_econ["geography"].value_counts())

Missing geography: 0

Rows by geography:
geography
Canada                       5
British Columbia             3
Alberta                      3
Newfoundland and Labrador    3
Prince Edward Island         3
Nova Scotia                  3
New Brunswick                3
Quebec                       3
Ontario                      3
Manitoba                     3
Saskatchewan                 3
Nunavut                      1
Northwest Territories        1
Yukon                        1
Name: count, dtype: int64

In [27]:
df_econ["value_original"] = df_econ["value"]

df_econ["numeric_value"] = (

    df_econ["value"]

    .astype(str)

    .str.replace("$", "", regex=False)

    .str.replace(",", "", regex=False)

    .str.replace("%", "", regex=False)

    .str.strip()

)

df_econ["numeric_value"] = pd.to_numeric(

    df_econ["numeric_value"],

    errors="coerce"

)

df_econ[

    ["indicator", "geography", "value_original", "numeric_value"]

].head(20)

,indicator,geography,value_original,numeric_value
10,Average weekly earnings,Canada,"$1,347.14",1347.14
13,Average weekly earnings,Nunavut,"$1,844.70",1844.70
14,Average weekly earnings,Northwest Territories,"$1,821.38",1821.38
15,Average weekly earnings,Yukon,"$1,504.26",1504.26
16,Average weekly earnings,British Columbia,"$1,356.78",1356.78
17,Average weekly earnings,Alberta,"$1,399.61",1399.61
26,Average weekly earnings,Newfoundland and Labrador,"$1,317.98",1317.98
27,Average weekly earnings,Prince Edward Island,"$1,207.99",1207.99
28,Average weekly earnings,Nova Scotia,"$1,228.91",1228.91
29,Average weekly earnings,New Brunswick,"$1,261.88",1261.88
30,Average weekly earnings,Quebec,"$1,279.96",1279.96
31,Average weekly earnings,Ontario,"$1,391.19",1391.19
32,Average weekly earnings,Manitoba,"$1,217.11",1217.11
33,Average weekly earnings,Saskatchewan,"$1,325.24",1325.24
75,Consumer Price Index,Canada,,NaN
89,Employment level,Prince Edward Island,"96,000",96000.00
90,Employment level,Nova Scotia,"541,000",541000.00
91,Employment level,New Brunswick,"409,000",409000.00
92,Employment level,Quebec,"4,589,000",4589000.00
93,Employment level,Ontario,"8,307,000",8307000.00

In [29]:
unit_map = {

    "Average weekly earnings": "Dollars",

    "Consumer Price Index": "Index",

    "Employment level": "Persons",

    "Unemployment rate": "Percent",

    "Real GDP by expenditure": "Index"

}

df_econ["unit"] = df_econ["indicator"].map(unit_map)

df_econ[

    ["indicator", "value_original", "numeric_value", "unit"]

].drop_duplicates()

                   indicator value_original  numeric_value     unit
10   Average weekly earnings      $1,347.14        1347.14  Dollars
13   Average weekly earnings      $1,844.70        1844.70  Dollars
14   Average weekly earnings      $1,821.38        1821.38  Dollars
15   Average weekly earnings      $1,504.26        1504.26  Dollars
16   Average weekly earnings      $1,356.78        1356.78  Dollars
17   Average weekly earnings      $1,399.61        1399.61  Dollars
26   Average weekly earnings      $1,317.98        1317.98  Dollars
27   Average weekly earnings      $1,207.99        1207.99  Dollars
28   Average weekly earnings      $1,228.91        1228.91  Dollars
29   Average weekly earnings      $1,261.88        1261.88  Dollars
30   Average weekly earnings      $1,279.96        1279.96  Dollars
31   Average weekly earnings      $1,391.19        1391.19  Dollars
32   Average weekly earnings      $1,217.11        1217.11  Dollars
33   Average weekly earnings      $1,325.24        1325.24  Dollars
75      Consumer Price Index                           NaN    Index
89          Employment level         96,000       96000.00  Persons
90          Employment level        541,000      541000.00  Persons
91          Employment level        409,000      409000.00  Persons
92          Employment level      4,589,000     4589000.00  Persons
93          Employment level      8,307,000     8307000.00  Persons
94          Employment level        756,000      756000.00  Persons
95          Employment level        622,000      622000.00  Persons
96          Employment level      2,661,000     2661000.00  Persons
97          Employment level     21,173,000    21173000.00  Persons
98          Employment level        245,000      245000.00  Persons
99          Employment level      2,949,000     2949000.00  Persons
100        Unemployment rate           6.9%           6.90  Percent
101        Unemployment rate           6.0%           6.00  Percent
102        Unemployment rate           6.8%           6.80  Percent
103        Unemployment rate           6.5%           6.50  Percent
104        Unemployment rate           5.0%           5.00  Percent
105        Unemployment rate           6.4%           6.40  Percent
106        Unemployment rate           8.6%           8.60  Percent
107        Unemployment rate           7.9%           7.90  Percent
108        Unemployment rate           6.1%           6.10  Percent
109        Unemployment rate           7.3%           7.30  Percent
110        Unemployment rate           5.6%           5.60  Percent
115  Real GDP by expenditure                           NaN    Index

In [31]:
df_econ["growth_numeric"] = (

    df_econ["growth_rate"]

    .astype(str)

    .str.extract(r"([-+]?\d*\.?\d+)")[0]

)

df_econ["growth_numeric"] = pd.to_numeric(

    df_econ["growth_numeric"],

    errors="coerce"

)

df_econ[

    [

        "indicator",

        "geography",

        "growth_rate",

        "growth_numeric",

        "growth_details"

    ]

].head(20)

,indicator,geography,growth_rate,growth_numeric,growth_details
10,Average weekly earnings,Canada,3.2%,3.2,(12-month change)
13,Average weekly earnings,Nunavut,2.3%,2.3,(12-month change)
14,Average weekly earnings,Northwest Territories,4.8%,4.8,(12-month change)
15,Average weekly earnings,Yukon,1.1%,1.1,(12-month change)
16,Average weekly earnings,British Columbia,4.4%,4.4,(12-month change)
17,Average weekly earnings,Alberta,2.5%,2.5,(12-month change)
26,Average weekly earnings,Newfoundland and Labrador,1.7%,1.7,(12-month change)
27,Average weekly earnings,Prince Edward Island,4.1%,4.1,(12-month change)
28,Average weekly earnings,Nova Scotia,5.6%,5.6,(12-month change)
29,Average weekly earnings,New Brunswick,5.3%,5.3,(12-month change)
30,Average weekly earnings,Quebec,1.9%,1.9,(12-month change)
31,Average weekly earnings,Ontario,3.6%,3.6,(12-month change)
32,Average weekly earnings,Manitoba,3.1%,3.1,(12-month change)
33,Average weekly earnings,Saskatchewan,4.4%,4.4,(12-month change)
75,Consumer Price Index,Canada,3.0%,3.0,(12-month change)
89,Employment level,Prince Edward Island,-0.4%,-0.4,(monthly change)
90,Employment level,Nova Scotia,0.5%,0.5,(monthly change)
91,Employment level,New Brunswick,0.6%,0.6,(monthly change)
92,Employment level,Quebec,-0.4%,-0.4,(monthly change)
93,Employment level,Ontario,-0.2%,-0.2,(monthly change)

In [33]:
df_econ["release_date"] = pd.to_datetime(

    df_econ["release_date"],

    errors="coerce"

)

print(df_econ["release_date"].dtype)

print(df_econ["release_date"].min())

print(df_econ["release_date"].max())

datetime64[ns]
2026-08-28 00:00:00
2026-09-24 00:00:00

In [35]:
print("Shape:", df_econ.shape)

print("\nMissing values:")

print(df_econ.isna().sum())

print("\nDuplicate rows:")

print(df_econ.duplicated().sum())

print("\nRows by indicator:")

print(df_econ["indicator"].value_counts())

Shape: (38, 14)

Missing values:
indicator_number    0
geo_code            0
indicator           0
value               0
reference_period    0
source              0
release_date        0
growth_rate         0
growth_details      0
geography           0
value_original      0
numeric_value       2
unit                0
growth_numeric      0
dtype: int64

Duplicate rows:
0

Rows by indicator:
indicator
Average weekly earnings    14
Employment level           11
Unemployment rate          11
Consumer Price Index        1
Real GDP by expenditure     1
Name: count, dtype: int64

In [37]:
missing_numeric = df_econ[

    df_econ["numeric_value"].isna()

][

    [

        "indicator",

        "geography",

        "value_original",

        "numeric_value",

        "growth_rate",

        "growth_numeric",

        "reference_period"

    ]

]

missing_numeric

,indicator,geography,value_original,numeric_value,growth_rate,growth_numeric,reference_period
75,Consumer Price Index,Canada,,NaN,3.0%,3.0,August 2026
115,Real GDP by expenditure,Canada,,NaN,0.8%,0.8,Second quarter 2026

In [39]:
final_columns = [

    "indicator_number",

    "indicator",

    "geo_code",

    "geography",

    "value_original",

    "numeric_value",

    "reference_period",

    "release_date",

    "growth_rate",

    "growth_numeric",

    "growth_details",

    "source"

]

df_econ_clean = df_econ[final_columns].copy()

df_econ_clean.head()

,indicator_number,indicator,geo_code,geography,value_original,numeric_value,reference_period,release_date,growth_rate,growth_numeric,growth_details,source
10,1,Average weekly earnings,0,Canada,"$1,347.14",1347.14,July 2026,2026-09-24,3.2%,3.2,(12-month change),14100223
13,1,Average weekly earnings,13,Nunavut,"$1,844.70",1844.70,July 2026,2026-09-24,2.3%,2.3,(12-month change),14100223
14,1,Average weekly earnings,12,Northwest Territories,"$1,821.38",1821.38,July 2026,2026-09-24,4.8%,4.8,(12-month change),14100223
15,1,Average weekly earnings,11,Yukon,"$1,504.26",1504.26,July 2026,2026-09-24,1.1%,1.1,(12-month change),14100223
16,1,Average weekly earnings,10,British Columbia,"$1,356.78",1356.78,July 2026,2026-09-24,4.4%,4.4,(12-month change),14100223

In [41]:
print("Final shape:", df_econ_clean.shape)

print("\nMissing values:")

print(df_econ_clean.isna().sum())

print("\nDuplicate rows:")

print(df_econ_clean.duplicated().sum())

print("\nIndicators:")

print(df_econ_clean["indicator"].value_counts())

print("\nGeographies:")

print(df_econ_clean["geography"].value_counts())

print("\nData types:")

print(df_econ_clean.dtypes)

Final shape: (38, 12)

Missing values:
indicator_number    0
indicator           0
geo_code            0
geography           0
value_original      0
numeric_value       2
reference_period    0
release_date        0
growth_rate         0
growth_numeric      0
growth_details      0
source              0
dtype: int64

Duplicate rows:
0

Indicators:
indicator
Average weekly earnings    14
Employment level           11
Unemployment rate          11
Consumer Price Index        1
Real GDP by expenditure     1
Name: count, dtype: int64

Geographies:
geography
Canada                       5
British Columbia             3
Alberta                      3
Newfoundland and Labrador    3
Prince Edward Island         3
Nova Scotia                  3
New Brunswick                3
Quebec                       3
Ontario                      3
Manitoba                     3
Saskatchewan                 3
Nunavut                      1
Northwest Territories        1
Yukon                        1
Name: count, dtype: int64

Data types:
indicator_number             int64
indicator                   object
geo_code                     int64
geography                   object
value_original              object
numeric_value              float64
reference_period            object
release_date        datetime64[ns]
growth_rate                 object
growth_numeric             float64
growth_details              object
source                      object
dtype: object

In [43]:
df_econ_clean.to_csv(

    "economic_indicators_clean.csv",

    index=False,

    encoding="utf-8-sig"

)

print("File exported successfully")

print(df_econ_clean.shape)

File exported successfully
(38, 12)

In [45]:
import os

print(os.path.abspath("economic_indicators_clean.csv"))

print(os.path.exists("economic_indicators_clean.csv"))

/Users/yuanquan0901/economic_indicators_clean.csv
True

In [47]:
import os

output_path = os.path.join(

    os.path.dirname(file_path),

    "economic_indicators_clean.csv"

)

df_econ_clean.to_csv(

    output_path,

    index=False,

    encoding="utf-8-sig"

)

print("Saved to:")

print(output_path)

Saved to:
/Users/yuanquan0901/Desktop/BSMM 8730/group project/economic_indicators_clean.csv